from pathlib import Path
import json, re, html, runpy
P=Path(__file__).resolve().parent
ns=runpy.run_path(str(P.parent/'build_dashboard.py'))
M=json.loads((P/'decision_model.json').read_text(encoding='utf-8'))
def render(name):
    out=ns['md']((P/name).read_text(encoding='utf-8'))
    return re.sub(r'\[([^\]]+)\]\(([^\s)]+\.md)\)',lambda m:'<a href="ready/'+html.escape(m[2])+'">'+m[1]+'</a>',out)
payload=dict(model=M,memo=render('INVESTMENT_DECISION_MEMO.md'),policy=render('WEEKLY_POLICY_V2.md'),reports={k:render(k+'.md') for k in ['technology','quality_compounders','financials','airbnb','industrials_payments']})
js=r'''
const PACK=__PACK__;
const MODEL=PACK.model;
const newKeys=new Set(['decisions','allocation','valuations','process']);
TABS.forEach(t=>{if(!t[1].startsWith('Archive'))t[1]='Audit archive · '+t[1];});
TABS.unshift(['decisions','Current decisions'],['allocation','Capital & risk'],['valuations','14 valuation models'],['process','Weekly policy & memo']);
const dpMoney=v=>Number(v).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const dpPct=v=>(100*v).toFixed(1)+'%';
const dpTable=(headers,rows)=>'<div class="scroll"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
R.decisions=()=>{
 $('#app').innerHTML=title('WEEKLY DECISION REVIEW · 27 SEP 2026','Two retained entry candidates. No increase in exposure.','Weekly review: 34 fresh price checks, three parallel audits, 42 operating cases retained. Initial 19% equity; maximum25%. New findings and exact coverage are in the weekly memo.')+
 `<div class="tally"><div><b>AMP ≤ $500</b><strong>First direct-stock candidate</strong><p class="sm mute">Up to 2% of capital; verify live price and thesis.</p></div><div><b>PAYX ≤ $101.80</b><strong>Second direct-stock candidate</strong><p class="sm mute">Up to 2%; ceiling includes the dividend-tax and fee challenge.</p></div><div><b>19% → 25%</b><strong>Initial / maximum equity</strong><p class="sm mute">15% index plus 4% initially eligible stocks; direct sleeve capped at 10%.</p></div><div><b>−18.0%</b><strong>Full-allocation tail stress</strong><p class="sm mute">A constructed scenario, not a guaranteed loss ceiling.</p></div></div>
 <div class="grid"><div class="card hi"><h3>Act on limits, not stale quotes</h3><p>AMP $493.00 and PAYX $101.37 remain below their ceilings at the September 25 close. Use live quotes and confirm events before buying. MSFT is corrected to $516.17. No entry ceilings or weights increased.</p><p>MSFT ≤ $500 · NVDA ≤ $215 · ALLE ≤ $145 · HIG ≤ $120 are funded conditional slots. HIG also requires the post-close settlement/capital bridge. Its accounting gain does not raise core EPS. Recheck business facts and issuer event calendars before any entry.</p></div><div class="card"><h3>The return tradeoff is explicit</h3><p>The reserve-heavy model's base planning outcome is about <b>4.3% annually initially</b>, or <b>4.9% if every slot fills</b>. These are scenario calculations, not promised returns.</p><p>Weekly review does not mean weekly trading. No orders, daily monitoring or personal liquidation instructions are active.</p></div></div>
 <div class="controls"><button onclick="go('allocation')">Explore the $50k / $100k plan</button><button onclick="go('valuations')">Inspect operating cases</button><a href="ready/Investment_Decision_Model.xlsx" download>Download editable model</a><a href="ready/Investment_Decision_Memo.pdf" download>Download investment memo</a></div>
 <div class="callout">New audit findings: AMP repurchase/book-value inconsistency in Claude v011; PAYX cash recovery remains unproved; HIG settlement affects GAAP earnings but not core EPS. <a href="weekly/2026-09-27/WEEKLY_REVIEW.md">Read the dated weekly review</a> · <a href="weekly/2026-09-27/ACTION_TABLE.csv">34-name action journal</a></div><h2>The ranked action list</h2><p class="sm mute">Ranks are judgments within the original 14 names. Return column: base annual IRR at the entry limit after illustrative 30% dividend withholding and25bp entry/exit costs, before capital-gains tax. AVOID means no new purchase at the reference price.</p>`+
 dpTable(['Rank / stock','Action','Reference / date','Entry ceiling','Base IRR at entry','Full direct slot'],MODEL.stocks.map(s=>[s.rank+' · <b>'+s.ticker+'</b>',s.decision,dpMoney(s.reference_price)+'<br><span class="sm mute">'+s.reference_date+'</span>',dpMoney(s.limit_price),dpPct(s.scenarios.find(x=>x.name==='base').irr_limit_after_30pct_withholding_25bp_costs),s.slot_weight?dpPct(s.slot_weight):'Replacement candidate']))+
 `<div class="callout">The earlier 25 tabs are retained as an audit archive. Their old all-WATCH messages, original weights and disputed return probabilities do not govern this replacement. The three deep data audits remain available in that archive.</div>`;
};
R.allocation=()=>{
 $('#app').innerHTML=title('CAPITAL ALLOCATION · USD · NO LEVERAGE','Keep the portfolio inside a deliberate risk budget.','Initial targets: 15% index, 2% AMP, 2% PAYX, 80% short Treasury fund, 1% cash. Unfilled future stock slots remain in reserve.')+
 `<div class="grid"><div class="card hi"><h3>Capital illustration</h3><label>Capital <select id="dpCapital"><option value="50000">$50,000</option><option value="100000" selected>$100,000</option></select></label><div id="dpHoldings"></div><p class="sm mute">Whole shares use stock ceilings and September 25 ETF NAVs, not live order prices. Refresh prices and dealing fees before sizing. IB01 is a Treasury fund, not guaranteed cash.</p></div><div class="card"><h3>Funded capacity</h3><p>Full direct-stock slots: AMP 2%, PAYX 2%, MSFT 2%, NVDA 1.5%, ALLE 1.5%, HIG 1%. Total direct 10%, plus index 15%; reserve at least75%.</p><p>Direct-name cap 2%; known issuer look-through planning cap 3.5%. At full target, dated VUAA holdings imply NVIDIA 2.712% and Microsoft 2.854% total exposure.</p><p>VUAA: USD London, IE00BFMXXD54. IB01: USD London, IE00BGSF1X88. Confirm broker and tax eligibility. The displayed GBP VUAG price is a different trading line.</p></div></div>
 <h2>Correlated stress—not a probability forecast</h2><div id="dpStress"></div><p class="sm mute">The tail test changed the design from 30% to25% equities. A total equity wipeout can still lose25% at full deployment, before reserve or currency effects. A stop order cannot guarantee an exit.</p>
 <h2>Three-year endpoint planning</h2>`+
 dpTable(['Case','Index annual assumption','Reserve annual assumption','Initial wealth CAGR','All slots filled CAGR'],MODEL.portfolio_scenarios.map(x=>[x.name,dpPct(x.index_annual_assumption),dpPct(x.reserve_annual_assumption),dpPct(x.initial_wealth_cagr),dpPct(x.full_wealth_cagr)]))+
 `<p class="sm mute">Direct dividends are reduced30% and held as cash; index/reserve compound. Full case hypothetically fills all slots immediately at limits. These assumptions do not capture the worst intra-period loss. Personal capital-gains tax, trading/FX costs excluded.</p>`;
 const draw=()=>{const cap=Number($('#dpCapital').value),p=MODEL.portfolios.find(x=>x.capital===cap);$('#dpHoldings').innerHTML=dpTable(['Holding','Units','Cost','Weight'],p.rows.map(r=>[r.ticker,r.whole_shares??'—',dpMoney(r.cost),dpPct(r.weight)]));$('#dpStress').innerHTML=dpTable(['Scenario','Index / stocks / reserve','Initial loss','Full loss','Full dollar loss'],MODEL.stresses.map(x=>[x.name,dpPct(x.core_shock)+' / '+dpPct(x.direct_shock)+' / '+dpPct(x.reserve_shock),dpPct(x.initial_loss),dpPct(x.full_loss),dpMoney(cap*x.full_loss)]));};$('#dpCapital').onchange=draw;draw();
};
R.valuations=()=>{
 $('#app').innerHTML=title('42 SCENARIOS · SOURCED FACTS ≠ ASSUMPTIONS','Inspect the earnings, multiple and downside.','Three-year holding horizon to September2029. Fiscal-year conventions, stock compensation, taxes and cash-flow definitions are explicit in the company memoranda.')+
 `<div class="controls"><label>Company <select id="dpStock">${MODEL.stocks.map(s=>`<option value="${s.ticker}">${s.rank}. ${s.ticker} · ${s.name}</option>`).join('')}</select></label><label>Dividend withholding <select id="dpTax"><option value="0">0% · gross</option><option value="30" selected>30% · sensitivity</option></select></label></div><div id="dpCase"></div>`;
 const draw=()=>{const s=MODEL.stocks.find(x=>x.ticker===$('#dpStock').value),tax=$('#dpTax').value==='30';$('#dpCase').innerHTML=`<h2>${s.ticker}: ${s.decision} · ceiling ${dpMoney(s.limit_price)}</h2><div class="grid"><div class="card"><h3>The case</h3><p>${safe(s.thesis)}</p><p><b>Reference:</b> ${dpMoney(s.reference_price)} on ${s.reference_date}. <b>Required return:</b> ${dpPct(s.hurdle)}.</p><p><b>Terminal earnings:</b> ${safe(s.terminal_period)}</p></div><div class="card"><h3>What can break it</h3><p>${safe(s.countercase)}</p><p>${safe(s.failure_rule)}</p><p class="sm mute">${safe(s.condition)}</p></div></div>`+dpTable(['Case','EPS / multiple','Terminal price','Annual dividends Y1 / Y2 / Y3','IRR at reference','IRR at limit','PV at hurdle'],s.scenarios.map(x=>[x.name,dpMoney(x.terminal_eps)+' / '+x.terminal_pe.toFixed(1)+'×',dpMoney(x.terminal_price),x.dividends.map(dpMoney).join(' / '),dpPct(tax?x.irr_reference_withholding30:x.irr_reference),dpPct(tax?x.irr_limit_withholding30:x.irr_limit),dpMoney(tax?x.pv_hurdle_withholding30:x.pv_hurdle)]))+`<p class="sm mute">No probability weights. Terminal bear losses are not maximum drawdowns. Selected tax treatment is a sensitivity, not a finding about your tax status. Dealing costs excluded from displayed IRR.</p><details><summary>September 26 baseline normalization, source tables and catalysts</summary><p class="sm mute">These preserved company memoranda contain older price references. Use the current table and September 27 weekly memo for prices, actions, events and limits.</p>${PACK.reports[s.detail_file.replace('.md','')]}</details>`;};$('#dpStock').onchange=draw;$('#dpTax').onchange=draw;draw();
};
R.process=()=>{$('#app').innerHTML=title('WEEKLY RESEARCH · SUNDAY 18:00 DUBAI','A repeatable decision process.','Refresh facts, valuation and risk; trade only when the evidence warrants it. Keep actual holdings separate from hypothetical slots.')+`<div class="controls"><a href="ready/Investment_Decision_Model.xlsx" download>Editable workbook</a><a href="ready/decision_table.csv" download>Decision CSV</a><a href="ready/scenarios.csv" download>42-scenario CSV</a><a href="ready/INVESTMENT_DECISION_MEMO.md" download>Full memo</a></div><details open><summary>Weekly policy — effective September 26; reviewed unchanged September 27</summary>${PACK.policy}</details><details><summary>Read the full decision memorandum</summary>${PACK.memo}</details>`;};
const auditGo=go;
go=function(k,t){auditGo(k,t);document.getElementById('reviewStatus').textContent=newKeys.has(k)?'CURRENT REPLACEMENT · 27 Sep 2026 · Dated conditional research · No orders placed':'AUDIT ARCHIVE · Preserved prior findings and original research. Current decisions are in the first four tabs.';};
cur='decisions';tabs();R[cur]();document.getElementById('reviewStatus').textContent='CURRENT REPLACEMENT · 27 Sep 2026 · Dated conditional research · No orders placed';
'''
htmlpath=P.parent/'Investment_Review.html'
doc=htmlpath.read_text(encoding='utf-8')
doc=doc.replace('</body>','<script>'+js.replace('__PACK__',json.dumps(payload,ensure_ascii=False).replace('</','<\\/'))+'</script></body>')
doc=doc.replace('</style>','select{padding:10px 12px;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:5px;font:inherit}.controls label{display:flex;align-items:center;gap:10px}.tally b{font-size:26px} </style>',1)
htmlpath.write_text(doc,encoding='utf-8')
print(json.dumps({'dashboard':str(htmlpath),'tabs':29,'preserved':25,'current':4,'bytes':len(doc.encode())}))
