import json, pathlib, hashlib, datetime
r=pathlib.Path('review/deep_audit'); d=r/'raw'; d.mkdir(exist_ok=True)
ms=[dict(symbol='MSFT',date=f'{y}-06-30',fiscalYear=str(y),period='FY',reportedCurrency='USD',filingDate=f'{y}-07-'+('29' if y==2026 else '30'),operatingCashFlow=c,capitalExpenditure=-p,freeCashFlow=c-p) for y,c,p in [(2026,182935000000,115948000000),(2025,136162000000,64551000000),(2024,118548000000,44477000000)]]
(d/'fmp_msft_cashflow_annual.json').write_text(json.dumps(ms,indent=2),encoding='utf-8')
prices=[dict(symbol='NVDA',date='2026-09-24',open=222.08,high=224.94,low=221.09,close=224.58,volume=77469856,change=2.5,changePercent=1.13,vwap=223.1725),dict(symbol='MSFT',date='2026-09-24',open=495.07,high=498.9,low=491.22,close=497.93,volume=16657643,change=2.86,changePercent=.5777,vwap=495.78)]
(d/'fmp_observed_price_responses.json').write_text(json.dumps(prices,indent=2),encoding='utf-8')
access=[dict(symbol=t,status='live_response' if t in ['NVDA','MSFT'] else 'blocked_402',sample_rejected=t not in ['NVDA','MSFT']) for t in 'NVDA CPAY AMP RL AME SNA ABNB NTAP PAYX MSFT IBKR HIG ALLE AIZ'.split()]
record=dict(audit_date_dubai='2026-09-26',retrieval_date_utc='2026-09-25',capture_completed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),provider='Financial Modeling Prep',access='Authenticated existing Free plan via user-provided dashboard and API Viewer; no credential retained',price_endpoint='https://site.financialmodelingprep.com/playground/historical-price-eod-full',price_parameters={'from':'2026-09-24','to':'2026-09-24'},price_access=access,cashflow_endpoint='https://site.financialmodelingprep.com/playground/cashflow-statement',cashflow_parameters={'limit':3,'period':'annual default after removing Q1'},files=[{'path':'raw/fmp_nvda_cashflow_annual.json','capture':'Full vendor JSON downloaded through Export menu'},{'path':'raw/fmp_msft_cashflow_annual.json','capture':'Selected fields transcribed from actual full response displayed in Raw UI; export download did not complete. Not a byte-for-byte raw payload.'},{'path':'raw/fmp_observed_price_responses.json','capture':'Full two public price objects transcribed from observed UI responses; not transport-level response capture.'}],financial_datasets='User-linked plugin page showed Install plugin; no callable connector found, no authenticated Financial Datasets values acquired.',limitations=['FMP annual validation does not itself validate TTM definitions or forecasts','Optional zero-valued interestPaid/incomeTaxesPaid require filing corroboration; not established true zeros','403/402 or bundled sample data must never pass instrument/date identity validation','Common issuer origin is distinct from independent extraction','Response-level ingestion timestamps are capture-window dates; precise per-request network times were not retained'])
for f in record['files']: f['sha256']=hashlib.sha256((r/f['path']).read_bytes()).hexdigest()
(r/'00_provider_access_ledger.json').write_text(json.dumps(record,indent=2),encoding='utf-8')
print('Saved credential-free provider evidence: 2 price responses, 14 access results, 2 annual financial series.')
