import json, hashlib
from pathlib import Path
from datetime import datetime, timezone

root=Path(__file__).resolve().parent.parent
raw=root/'raw_filing'
docs=json.loads((raw/'document_manifest.json').read_text())
indexes=json.loads((raw/'submissions_manifest.json').read_text())
summary=json.loads((raw/'submissions_summary.json').read_text())
for doc in docs:
    assert hashlib.sha256((raw/doc['file']).read_bytes()).hexdigest()==doc['sha256']
bridge={'net_income':45.9,'noncash_net':-57.3,'receivables':-54.4,'prepayments':-49.3,'payables_current_liabilities':-181.6,'deferred_costs':-17.6,'other':9.4}
assert round(sum(bridge.values()),1)==-304.9
findings=[
 {'id':'HIG-SETTLEMENT','ticker':'HIG','status':'new_after_price_cutoff','source':'HIG_20260925_8K.html','locator':'Items 1.02 and 7.01','accepted_utc':'2026-09-25T20:18:34Z','period':'Expected three and nine months ending 2026-09-30','units':'USD millions','facts':{'cash_received':1120,'expected_pretax_gain':497,'expected_gaap_net_income_gain':393,'core_earnings_effect':0},'basis':'One-time GAAP gain, excluded from non-GAAP core earnings','action':'No normalized-EPS uplift. Entry120 provisional only; wait for settlement receivable/deferred gain/tax/statutory-capital bridge.'},
 {'id':'HIG-EXHAUSTED-COVER','ticker':'HIG','status':'context_corrects_initial_risk_inference','source':'HIG_Q22026_10Q.html','locator':'MD&A Reinsurance for Asbestos and Environmental Reserve Development, pp90-91','period':'As of2025-12-31 and2026-06-30','units':'USD millions','facts':{'original_aggregate_limit':1500,'attachment':1700,'unused_limit_at_dec2025':0,'deferred_gain_jun2026':814,'deferred_gain_dec2025':850},'action':'Do not characterize settlement as giving up1500 of unused protection. Residual reserve risk pre-existed. Disputed recoveries were suspended afterQ1.'},
 {'id':'PAYX-CFO','ticker':'PAYX','status':'already_in_codex_v005_not_new_economic_discovery','source':'PAYX_Q1FY27_10Q.html','locator':'Cash-flow statement p4; MD&A pp26-27','accepted_utc':'2026-09-24T20:06:01Z','period':'Three months ended2026-08-31 vs2025-08-31','units':'USD millions','facts':{'cfo_current':413.5,'cfo_prior':718.4,'capex_current':56.1,'capex_prior':55.9,'fcf_current':357.4,'fcf_prior':662.5,'dividends_current':424.1},'formula':'FCF=CFO-cash PPE; year-on-year delta=current-prior','cfo_delta_bridge':bridge,'definition_warning':'PEO payroll settlements affect CFO; ordinary client-fund obligations financing. Qualitative explanation does not prove reversal.','inherited_diagnostic':{'ttm_fcf':2016.7,'owner_cash':1711.5,'failure_threshold':1700,'threshold_cushion':11.5},'action':'Keep small conditional starter limit101.80 and FY2027 normalizedEPS5.85; do not add before cash recovery evidence. Correct strict Sep24 close cutoff labeling.'},
 {'id':'RSG-FCF-DEFINITION','ticker':'RSG','status':'inherited_full_conviction_not_validated','source':'RSG_Q22026_release.html','locator':'Cash-flow statement p7 and adjusted-FCF reconciliation p12','period':'Six months ended2026-06-30','units':'USD millions','facts':{'cfo':2380,'cash_ppe':868,'ppe_received':809,'asset_proceeds':7,'restructuring_addback':5,'conventional_fcf':1512,'cash_fcf_including_disposals':1519,'company_adjusted_fcf':1583},'formula':'2380-868=1512;2380-868+7=1519;2380-809+7+5=1583','action':'Correct64 difference. Need unleveredFCF/EV/WACC or equitycash/equityvalue/CoE; do not use levered CFO-capex directly with EV/WACC.7% sizing not adopted.'},
 {'id':'LH-PERIOD-DEBT','ticker':'LH','status':'correct_claude_v011_period_and_classification','source':'LH_Q22026_10Q.html','locator':'Condensed balance sheet; cash-flow statement p7; Note3 p11 and debt note','period':'2026-06-30 vs2025-12-31; six months not one quarter','units':'USD millions','facts':{'longterm_debt_jun':5857.6,'longterm_debt_dec':5084.6,'current_debt_jun':0.9,'current_debt_dec':500.1,'total_borrowing_change':273.8,'h1_cash_acquisitions':427.9,'h1_buybacks':451.8,'term_loan_mar20':750,'notes_repaid_jun1':500},'formula':'(5857.6+0.9)-(5084.6+500.1)=273.8','action':'Replace one-quarter773m debt-increase claim. Require finite-growth/fade valuation; perpetual3.1% versus finite7-8% is not sufficient.5.6% sizing not adopted.'},
 {'id':'LH-PAMA','ticker':'LH','status':'pre_cutoff_material_risk_missing_from_thesis_detail','source':'LH_20260922_8K.html','locator':'Item7.01','period':'2027-2029 preliminary reimbursement rates;2026-2029 company outlook','units':'percent','facts':{'reaffirmed_revenue_cagr':[5,8],'reaffirmed_adjusted_eps_cagr':[8.5,11.5]},'action':'Model reimbursement sensitivity. Reaffirmation is management forecast, not proof proposed cuts are immaterial; impact guidance expectedFebruary2027.'},
 {'id':'NTAP-144','ticker':'NTAP','status':'new_filing_no_fundamental_revision','source':'NTAP_20260924_144.xml','locator':'securitiesInformation and noticeSignature','accepted_utc':'2026-09-24T20:24:29Z','period':'Proposed sale2026-09-24, plan2026-06-15','units':'shares','facts':{'proposed_shares':37000},'action':'No EPS or entry change; proposed sale is not execution confirmation.'}
]
payload={'prepared_utc':datetime.now(timezone.utc).isoformat(),'author':'Codex filing-audit agent','parents':['v005_2026-09-26_codex','v011_2026-09-27_claude'],'status':'bounded audit, not trade authorization','cutoffs':{'strict_old_price_information':'2026-09-24T20:00:00Z','last_market_close':'2026-09-25T20:00:00Z','next_five_trading_days':['2026-09-28','2026-09-29','2026-09-30','2026-10-01','2026-10-02']},'findings':findings,'documents':docs,'submission_index_manifest':indexes,'submission_index_observations':summary,'calendar_gate':{'confirmed_event_next5_found':False,'all_names_cleared':False,'status':'Not found is not verified no event. MSFT date unannounced; ALLE no upcomingdetails; AMP/HIG/NVDA dynamiccalendar incomplete; others requirecomplete refresh.'},'verification_review':{'x1_v005_verification':'No demonstrated normalizedEPS arithmetic error for AMP/PAYX. PAYX20x historical-range concern is judgment with secondaryvendor support. Priceconflicts delegated.','adopt':['Primarytable facts','PAYX cash recovery gate','AMP/PAYX disclosed normalizedEPS assumptions'],'change':['Cutoff timestamps','HIG one-time settlement watch','LH debtperiod/totaldebt comparison','RSG cashdefinition'],'reject':['Automatic inheritance of RSG7%/LH5.6% conviction weights','LeveredFCF against EV/WACC withoutbridge','Perpetualgrowth vs finitegrowth as valuation proof']},'limitations':['SEC index absence does not prove no news','No broad re-underwriting of all14','No verified future cash recovery','Calendar not fully cleared','No trades performed']}
(root/'filing_audit.json').write_text(json.dumps(payload,indent=2),encoding='utf-8')
print('Written filing_audit.json; verified7 document hashes and CFO delta bridge')
