import json
N={
'GEN':['Q1 FY27 (to 3 Jul 2026): revenue beat its own guidance range; non-GAAP EPS grew high-teens; full-year guidance raised.','Model sees it as deep value: about 7x forward earnings with 5 guidance raises in 9 quarters.','Watch: acquisition-funded balance sheet (check leverage); consumer cyber-safety is a mature market.'],
'HPE':['Fiscal Q3 2026: record revenue of $12.2B, up 34%; operating profit also a record.','Raised outlook for both fiscal 2026 and 2027 on record order backlog; plans to return at least 75% of free cash flow in Q4.','Watch: most volatile holding (about 57% a year); AI-server margins are thin and lumpy.'],
'FIX':['Q2 2026: revenue $3.27B vs $2.17B a year ago (+51%); EPS $12.53 vs $6.53; operating cash flow $1.14B.','Mechanical and electrical contractor riding data-centre and factory construction.','Watch: does not issue formal guidance; 27x forward P/E; construction cycles turn fast; about 57% volatility.'],
'ADSK':['Fiscal Q2 2027: revenue +16% to $2.05B.','Raised full-year billings and revenue growth guidance, partly from the MaintainX acquisition; margin guidance held.','Watch: acquisition integration; AI disruption risk to design software is debated.'],
'SWK':['Q2 2026: sales $4.0B flat (organic +3%); gross margin up about 6 points; free cash flow $698M.','Raised 2026 GAAP EPS range to $4.60 to $5.45.','Watch: about 2.5 points of that margin gain came from one-off tariff refunds, so underlying improvement is smaller than the headline.'],
'GPN':['Q2 2026: adjusted EPS $3.46 (+12%), but GAAP EPS only $0.05 because of deal-related charges.','Normalised revenue +4%; $1.2B returned to shareholders year to date; capital-return plan reaffirmed.','Watch: big gap between adjusted and GAAP profit; slow growth; about 5x forward P/E prices in scepticism.'],
'BKNG':['Q2 2026: room nights +5%, gross bookings +9%, adjusted EPS +15%; beat guidance on every line.','Cost programme savings target raised to about $650M; heavy buybacks.','Watch: Middle East conflict hits long-haul travel; EU scrutiny of commissions.'],
'EXPE':['Q2 2026: gross bookings +12%, revenue +14%, with B2B +23%; beat guidance and raised full-year guidance.','B2B (powering other travel sellers) is the growth engine.','Watch: shares travel-cycle risk with BKNG (combined about 10% of the portfolio); about 51% volatility.'],
'VTRS':['Q2 2026: revenue $3.8B (+5%); adjusted EBITDA $1.2B; GAAP net loss of $119M.','Raised 2026 guidance midpoints for all metrics; about $550M returned; gross leverage down to 2.9x.','Watch: generic-drug pricing pressure; GAAP losses from charges.'],
'IVZ':['Q2 2026: record $45.1B of net long-term inflows (ETFs, index, private markets); AUM $2.5T.','Adjusted operating margin 37.5%.','Watch: fees fall with markets, so this is a leveraged bet on markets staying up; no formal guidance.'],
'BIIB':['Q2 2026: revenue $2.7B (+3%); newer drugs +24% to $1.06B.','Guidance updated for stronger underlying business; the Apellis acquisition dilutes 2026 EPS by about $0.85.','Watch: legacy multiple-sclerosis franchise decline; deal integration; biotech binary risk.'],
'BBY':['Q2 FY27: comparable sales +4.1%; adjusted EPS +15% to $1.47.','Raised FY27 comparable-sales guide to 1.9% to 3.0% and adjusted EPS guide to $6.70 to $6.90.','Watch: consumer-electronics demand is cyclical and tariff-exposed.'],
'ADI':['Fiscal Q3 2026: record revenue of $4.02B led by data centre and industrial; trailing free cash flow $4.9B (36% of revenue).','$1.7B returned in the quarter; guided to a record fourth quarter.','Watch: analog chips are cyclical; 23x forward P/E.'],
'AMP':['Q2 2026: adjusted operating EPS $11.07 (+22%); adjusted ROE 55%.','Wealth-management asset growth drives earnings.','Watch: market-linked; the third asset manager in the book (cap watched).'],
'DD':['Q2 2026: beat its own guidance and raised full-year 2026 guidance; organic sales +4%.','Free-cash-flow conversion 127%; announced $250M of buybacks for Q3.','Watch: post-separation execution; industrial demand cycle.'],
'NEM':['Q2 2026: about 1.3M ounces of gold; record Q2 free cash flow of $2.2B; on track for full-year guidance.','A cash machine while gold prices stay high.','Watch: pure gold-price bet (about 50% volatility); the release reader logged 3 guidance cuts in 2 years; you are already heavy in precious metals via India SIPs.'],
'NVDA':['Fiscal Q2 2027: revenue $96.2B, +106% year on year and +18% on the prior quarter; gross margin 75%.','Estimates rose about 24% in 90 days; only about 14x forward earnings.','Watch: beta about 2.2, the highest in the book; customers building their own chips. Audit note: EDGAR pulled the CFO commentary, not the press release, so its guidance score is treated as neutral.'],
'INCY':['Q2 2026: revenue $1.67B (+38%), flattered by a one-time CMS-related benefit; ex that, net sales +17%.','Raised 2026 net-sales guidance to $5.13B to $5.26B; Opzelura +173%.','Watch: Jakafi (about half of sales) faces patent expiry later this decade (verify date); valuation methods disagree widely (low confidence, small weight).'],
'JBHT':['Q2 2026: revenue $3.50B (+19%); operating income +32%; EPS $1.91 vs $1.31.','Freight recovery showing up in margins.','Watch: trucking is highly cyclical; no formal guidance; 23x forward P/E.'],
'TROW':['Q2 2026: record $1.9T AUM, but net client outflows of $6.5B; adjusted EPS $2.57.','Returned $441M via dividends and buybacks.','Watch: the steady shift from active funds to index funds (outflows) is structural; smallest weight for a reason.']}
d=json.load(open('dash2.json')); d['N2']=N
d['AL']=json.load(open('audit_loop1.json'))
d['grade2']=[('Universe & data breadth',10,'497 stocks, 11 yrs prices, statements, full estimate set'),('Primary-source reading',9,'467 SEC releases machine-read; 20 holdings read by hand (latest release)'),
 ('Valuation rigour',9,'3 methods, shrinkage, reverse DCF; new sensitivity test shows E ranges 12.4% to 15.9%'),('Out-of-sample validation',9,'3-yr point-in-time + 10-yr factor test; survivorship bias now measured (+6.3 pts/yr) and neutralised in the alpha estimate'),
 ('Risk modelling',9,'20k-path bootstrap incl. 2020/2022; resampled optimiser'),('Portfolio vs mandate',9,'Frontier with odds for 15/20/25/50%'),('Error discovery',10,'17 errors found and fixed'),
 ('Honesty of probabilities',10,'Shrunk vs raw; assumption ranges shown'),('Company-level qualitative depth',8,'Primary-source notes for all 20 holdings; still no call transcripts, expert calls or segment models'),('Actionability',9,'Exact weights; order sheet needs amount and broker')]
d['fix3']=[('NVDA release reader read the wrong exhibit','EDGAR returned NVIDIA\'s CFO commentary (exhibit 99.2), not the press release, so its guidance score was understated. Treated as neutral; the downloader regex needs "pr.htm" added.'),
 ('Survivorship bias was unmeasured','Compared with the real equal-weight S&P ETF (RSP), today\'s-constituent returns were inflated by 7.1, 7.3 and 4.6 points. The alpha estimate already compares like with like; absolute backtest returns are now labelled as inflated.')]
json.dump(d,open('dash2.json','w')); print('ok',sum(g[1] for g in d['grade2']))
