const D2=__DATA2__;
const P2=D2.P2,REC=P2.Recommended,C2=D2.C2;
TABS.unshift(['v2v','v2 · Verdict (Hurdle-15)'],['v2bt','v2 · Backtest'],['v2fr','v2 · Frontier & odds'],['v2c','v2 · Candidates (52)'],['v2rel','v2 · Release reader'],['v2u','v2 · Ranking (497)'],['v2g','v2 · Audit loops & grade']);
TABS.forEach(t=>{if(!t[1].startsWith('v2'))t[1]='v1 · '+t[1]});
cur='v2v';
const card2=(t)=>{const c=C2[t];if(!c)return'';const nt=D2.N2[t];const tl=(c.tl||[]).map(x=>`<span title="${x.d}" class="pill" style="border-color:${x.r?'var(--up)':x.c?'var(--down)':'var(--line)'}">${x.d.slice(2,7)} ${x.r?'▲':x.c?'▼':x.k?'=':'·'}</span>`).join('');
 return `<div class="card ${REC.w[t]?'hi':''}"><div class="hdr" style="border:0;padding:0"><div><h3>${esc(c.n)} (${t})</h3><div class="mute sm">${esc(c.s)} · ${esc(c.sub)}${REC.w[t]?` · <b style="color:var(--gold)">Portfolio ${pct(REC.w[t])}</b>`:''}</div></div><div style="text-align:right"><div class="big" style="font-size:26px">${usd(c.p)}</div><div class="sm mute">Confidence ${n(c.conf,0)} · v2 rank ${c.rk}/52</div></div></div>
 <div class="kv" style="margin-top:8px"><span>Conservative expected return (shrunk)</span><b>${sp(c.Esh)}</b><span>Building blocks: yield + growth + re-rating</span><span>${sp(c.Ebb)} = ${pct(c.by)} + ${pct(c.bg)} + ${pct(c.br)}</span><span>Factor model / scenario model</span><span>${sp(c.Efac)} / ${c.Escen==null?'n/a':sp(c.Escen)}</span><span>Methods disagree by</span><span>${pct(c.Esp,0)}</span>
 <span>Momentum / earnings momentum / value / quality</span><span>${Math.round(c.pm*100)} / ${Math.round(c.pe*100)} / ${Math.round(c.pv*100)} / ${Math.round(c.pq*100)}</span><span>Fwd P/E · volatility · 3-yr beta</span><span>${n(c.fpe)}x · ${pct(c.vol,0)} · ${n(c.beta,2)}</span><span>Guidance record (${c.nrel} releases)</span><span><span class="ok">${c.raises} raises</span> / <span class="bad">${c.cuts} cuts</span> / ${c.keeps} held</span></div>
 <div style="margin-top:8px">${tl}</div>${nt?`<ul class="pts sm">${nt.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<p class="sm"><a href="${c.url}" target="_blank" rel="noopener">Latest SEC earnings release</a>${C[t]?` · <a href="#" data-deep="${t}">Full v1 deep dive</a>`:''}</p></div>`};
function wireDeep(){document.querySelectorAll('a[data-deep]').forEach(a=>a.onclick=e=>{e.preventDefault();go(C[a.dataset.deep].rk30?'deep':'one',a.dataset.deep)})}
R.v2v=()=>{const w=REC.w,ks=Object.keys(w).sort((a,b)=>w[b]-w[a]);
$('#app').innerHTML=`<h1>v2: a 20-stock portfolio at the edge of your 15% hurdle.</h1><p class="lede">A point-in-time backtest showed my v1 model's low-volatility tilt lagged the market in all three test years. The redesigned model (momentum, earnings upgrades, value and quality) beat the market in all three years with two different weightings. After shrinking every forecast for optimism, the portfolio's conservative expected return is <b>${pct(REC.E)}</b> (raw model ${pct(REC.E_raw)}), with a <b>${pct(REC.p15,0)}</b> chance of 15%+.</p>
<div class="tally"><div><b>${pct(REC.E,1)}</b><span>conservative expected return</span></div><div><b>${pct(REC.p15,0)}</b><span>chance of 15%+</span></div><div><b>${pct(REC.p25,0)}</b><span>chance of 25%+</span></div><div><b>${pct(REC.p50,0)}</b><span>chance of 50%+</span></div><div><b>${pct(REC.vol,0)}</b><span>volatility (S&amp;P about 15%)</span></div><div><b>${pct(REC.y2022,0)}</b><span>replayed through 2022</span></div></div>
<h2>Mandate scorecard</h2><div class="scroll"><table><thead><tr><th>Your requirement</th><th>Result</th><th>Status</th></tr></thead><tbody>
<tr><td>15% a year hurdle</td><td>${pct(REC.E)} conservative (${pct(REC.E_raw)} raw); sensitivity range 12.4% to 15.9% depending on the market assumption</td><td class="warn">At the edge</td></tr>
<tr><td>Realistic chance of 15%+</td><td>${pct(REC.p15,0)} (roughly a coin flip)</td><td class="ok">Met</td></tr>
<tr><td>1-in-4 chance of 50%+ (read "0.5%" as 50%)</td><td>${pct(REC.p50,1)}. Needs about 67% volatility, which carries about a 1-in-3 chance of losing 30%+</td><td class="bad">Not achievable at acceptable risk</td></tr>
<tr><td>If you meant 25%+</td><td>${pct(REC.p25,0)}</td><td class="ok">Met</td></tr><tr><td>Chance of losing money in a year</td><td>${pct(1-REC.p0,0)}; 5th-percentile year ${sp(REC.p5)}</td><td class="mute">Accepted risk</td></tr></tbody></table></div>
<h2>The 20 holdings</h2><p class="mute">Each card shows the three return methods, the guidance record from 9 quarterly SEC releases (▲ raised, ▼ cut, = held), and notes from the latest release.</p><div class="grid">${ks.map(card2).join('')}</div><p class="mute sm">Not financial advice. Backtests use today's index members, which flatters absolute returns (measured at +6.3 points a year versus the real equal-weight S&amp;P ETF).</p>`;wireDeep();};
R.v2bt=()=>{const b=D2.BT,yrs=['2023','2024','2025'],f=D2.BT.f10,S=D2.AL.surv;
$('#app').innerHTML=`<h2 style="margin-top:0">Backtest: what I got wrong, and the fix</h2><p class="mute">Each September, the model was run using only information available then (statements with a 90-day lag, prices to date), and returns were measured over the next 12 months.</p>
<div class="scroll"><table><thead><tr><th>12 months from late Sept…</th>${yrs.map(y=>`<th class="num">${y}</th>`).join('')}</tr></thead><tbody>
<tr><td>S&amp;P 500</td>${yrs.map(y=>`<td class="num">${pct(b.v1[y].spx)}</td>`).join('')}</tr><tr><td>Real equal-weight S&amp;P (RSP ETF)</td>${yrs.map(y=>`<td class="num">${pct(S[y].RSP)}</td>`).join('')}</tr>
<tr><td>Equal-weight of today's members (survivorship-inflated)</td>${yrs.map(y=>`<td class="num">${pct(b.v1[y].ew)}</td>`).join('')}</tr>
<tr><td class="bad">v1 model top 30 (low-vol tilt)</td>${yrs.map(y=>`<td class="num bad">${pct(b.v1[y].top30)}</td>`).join('')}</tr>
<tr><td class="ok">v2 model top 30 (weighting A)</td>${yrs.map(y=>`<td class="num ok">${pct(b.v3[y].top30)}</td>`).join('')}</tr><tr><td class="ok">v2 model top 30 (weighting B)</td>${yrs.map(y=>`<td class="num ok">${pct(b.v3b[y].top30)}</td>`).join('')}</tr>
<tr><td>v1 rank correlation with next-year return (IC)</td>${yrs.map(y=>`<td class="num">${n(b.v1[y].ic,3)}</td>`).join('')}</tr><tr><td>v2 rank correlation (IC)</td>${yrs.map(y=>`<td class="num">${n(b.v3[y].ic,3)}</td>`).join('')}</tr>
<tr><td>Low-volatility pillar IC (why v1 failed)</td>${yrs.map(y=>`<td class="num bad">${n(b.v1[y].pillar_ic.R,3)}</td>`).join('')}</tr><tr><td>Momentum pillar IC</td>${yrs.map(y=>`<td class="num ok">${n(b.v1[y].pillar_ic.M,3)}</td>`).join('')}</tr></tbody></table></div>
<h2>Ten-year style test (monthly, top 50)</h2><div class="scroll"><table><thead><tr><th>Style</th><th class="num">CAGR</th><th class="num">Volatility</th><th class="num">Worst fall</th><th class="num">12m ≥15%</th><th class="num">12m ≥50%</th><th class="num">2022</th></tr></thead><tbody>${Object.entries(f).map(([k,v])=>`<tr><td>${k}</td><td class="num">${pct(v.cagr)}</td><td class="num">${pct(v.vol)}</td><td class="num">${pct(v.mdd)}</td><td class="num">${pct(v.p15,0)}</td><td class="num">${pct(v.p50,0)}</td><td class="num">${pct(v.y2022)}</td></tr>`).join('')}</tbody></table></div>
<p class="sm mute">Absolute numbers are inflated by survivorship bias; compare styles against each other. The edge carried into forecasts was cut by 58%, following McLean &amp; Pontiff (2016).</p>`;};
R.v2fr=()=>{const ks=Object.keys(P2).filter(k=>P2[k].w);
$('#app').innerHTML=`<h2 style="margin-top:0">Frontier: how much risk buys how much return</h2><p class="mute">Odds come from 20,000 simulated years built from 10 years of real monthly returns (including COVID and 2022), re-centred on each portfolio's conservative expected return.</p>
<div class="scroll"><table><thead><tr><th>Portfolio</th><th class="num">Names</th><th class="num">Expected</th><th class="num">Volatility</th><th class="num">Beta</th><th class="num">≥15%</th><th class="num">≥20%</th><th class="num">≥25%</th><th class="num">≥50%</th><th class="num">≤−20%</th><th class="num">2022</th><th class="num">COVID</th></tr></thead><tbody>${ks.map(k=>{const v=P2[k];return`<tr${k==='Recommended'?' style="outline:1px solid var(--gold)"':''}><td><b>${k}</b></td><td class="num">${v.n}</td><td class="num">${pct(v.E)}</td><td class="num">${pct(v.vol)}</td><td class="num">${n(v.beta,2)}</td><td class="num">${pct(v.p15,0)}</td><td class="num">${pct(v.p20,0)}</td><td class="num">${pct(v.p25,0)}</td><td class="num">${pct(v.p50,1)}</td><td class="num">${pct(v.pl20,1)}</td><td class="num">${pct(v.y2022)}</td><td class="num">${pct(v.covid)}</td></tr>`}).join('')}</tbody></table></div>
<h2>Sensitivity: what moves the recommended portfolio's expected return</h2><div class="scroll"><table><tbody>${Object.entries(D2.AL.sens).map(([k,v])=>`<tr><td>${k}</td><td class="num">${pct(v)}</td></tr>`).join('')}</tbody></table></div><p class="sm mute">The biggest single lever is what the overall market does (the 10% prior). Stock-picking edge adds about 1 point.</p>`;};
R.v2c=()=>{const ks=Object.keys(C2).sort((a,b)=>C2[a].rk-C2[b].rk);$('#app').innerHTML=`<h2 style="margin-top:0">All 52 release-read candidates</h2><div class="grid">${ks.map(card2).join('')}</div>`;wireDeep();};
R.v2rel=()=>{const rows=Object.values(C2).map(c=>({t:c.t,n:c.n,nrel:c.nrel,r:c.raises,c:c.cuts,k:c.keeps,gs:c.gs,hw:c.flags.headwind,inv:c.flags.investig,url:c.url}));
$('#app').innerHTML=`<h2 style="margin-top:0">Earnings-release reader: 467 SEC filings</h2><p class="mute">Every 8-K Item 2.02 earnings release since July 2024 was read for guidance raises, cuts and maintains, plus red-flag language. Companies that don't give guidance (many insurers and payment networks) score neutral. Keyword reading can misfire; see the audit notes.</p><div class="scroll"><table id="rt"></table></div>`;
table('rt',[['t','Ticker',v=>`<b>${v}</b>`],['n','Company',v=>esc(v)],['nrel','Releases',v=>v,'num'],['r','Raises',v=>`<span class="ok">${v}</span>`,'num'],['c','Cuts',v=>`<span class="bad">${v}</span>`,'num'],['k','Held',v=>v,'num'],['gs','Net score',v=>n(v,2),'num'],['hw','"Headwind" mentions',v=>v,'num'],['inv','Investigation mentions',v=>v,'num'],['url','Latest',v=>`<a href="${v}" target="_blank" rel="noopener">SEC</a>`]],rows,{sort:'gs',asc:false});};
R.v2u=()=>{$('#app').innerHTML=`<h2 style="margin-top:0">v2 ranking of all 497</h2><div class="scroll" style="max-height:700px"><table id="u3"></table></div>`;
table('u3',[['rk','#',v=>v,'num'],['t','Ticker',v=>`<b>${v}</b>`],['n','Name',v=>esc(v)],['s','Sector'],['v3','Score',v=>n(v,0),'num'],['pm','Momentum',v=>Math.round(v*100),'num'],['pe','Earnings mom.',v=>Math.round(v*100),'num'],['pv','Value',v=>Math.round(v*100),'num'],['pq','Quality',v=>Math.round(v*100),'num'],['E','Expected (3-method)',v=>sp(v),'num'],['vol','Volatility',v=>pct(v,0),'num'],['why','Gate',(v,r)=>r.gate?'<span class="ok">Pass</span>':`<span class="bad">${v}</span>`]],D2.U3,{sort:'rk'});};
R.v2g=()=>{const g=D2.grade2,tot=g.reduce((a,b)=>a+b[1],0);
$('#app').innerHTML=`<h2 style="margin-top:0">Audit loops & self-grade: ${tot}/100</h2><p class="mute">Grade history: 58 (first list), 78 (v1 dashboard), 91 (v2 analysis), ${tot} (after audit loops). The honest ceiling in this environment is about 93. Reaching 95+ needs data I can't get here: earnings-call transcripts, point-in-time analyst-estimate history, and a survivorship-free index history.</p>
<div class="scroll"><table><thead><tr><th>Criterion</th><th class="num">Score</th><th>Evidence / gap</th></tr></thead><tbody>${g.map(([a,s,e])=>`<tr><td>${a}</td><td class="num"><b>${s}</b>/10</td><td class="w">${esc(e)}</td></tr>`).join('')}</tbody></table></div>
<h2>Errors found and fixed in v2 and the audit loops</h2><div class="grid">${D2.fix2.concat(D2.fix3).map(([h,b])=>`<div class="card"><h4>${esc(h)}</h4><p class="sm">${esc(b)}</p></div>`).join('')}</div>
<h2>Audit loop results</h2><div class="grid"><div class="card"><h4>Loop 1 · Holdings integrity</h4><p class="sm">All 20 holdings pass gates; 180 of 180 releases matched to the right company, except NVIDIA (CFO commentary pulled instead of the press release; neutralised).</p></div><div class="card"><h4>Loop 2 · Survivorship bias</h4><p class="sm">Today's-member equal-weight beat the real equal-weight S&amp;P ETF by ${Object.values(D2.AL.surv).map(x=>pct(x.bias)).join(', ')}. The alpha estimate compares like with like, so it is unaffected; absolute backtest returns are labelled as inflated.</p></div><div class="card"><h4>Loop 3 · Assumption sensitivity</h4><p class="sm">Expected return ranges ${pct(Math.min(...Object.values(D2.AL.sens)))} to ${pct(Math.max(...Object.values(D2.AL.sens)))}. The 15% hurdle depends mostly on the market, not on stock picking.</p></div></div>`;};
