from pathlib import Path
import json,hashlib
r=Path('review')
p=r/'WEEKLY_INVESTMENT_POLICY.md';s=p.read_text(encoding='utf-8').replace('Sunday 18:00 Asia/Dubai, use latest completed US session. User has requested weekly refreshes; no automatic trading. This schedule is an editable default.','Weekly automation created and ACTIVE: Sunday 18:00 Asia/Dubai, using the latest completed US session. Automation id: weekly-investment-evidence-and-action-review. This schedule is editable. No automatic trading or daily monitoring.');p.write_text(s,encoding='utf-8')
p=r/'build_dashboard.py';s=p.read_text(encoding='utf-8').replace('Sunday 18:00 Dubai is the proposed weekly review time.','Weekly review is scheduled for Sunday 18:00 Dubai.');p.write_text(s,encoding='utf-8')
p=r/'INVESTMENT_COMMITTEE_REVIEW.md';s=p.read_text(encoding='utf-8').replace('## Account and tax structure','The weekly review is scheduled for **Sunday at 18:00 Asia/Dubai**, beginning 27 September 2026, using the latest completed US session. It is a research automation in this task, not brokerage execution or daily monitoring. Its first runs must continue closing evidence gaps, not mechanically recycle a watch list.\n\n## Account and tax structure');p.write_text(s,encoding='utf-8')
manifest=json.loads((r/'data/source_manifest.json').read_text());src=Path('source_bundle/equity_project'); changed=[x['file'] for x in manifest if hashlib.sha256((src/x['file']).read_bytes()).hexdigest()!=x['sha256']]
(r/'data/source_integrity_check.json').write_text(json.dumps({'files_checked':len(manifest),'changed_source_files':changed},indent=2))
(r/'data/automation_status.json').write_text(json.dumps({'automation_id':'weekly-investment-evidence-and-action-review','status':'ACTIVE','schedule_description':'Sunday 18:00 Asia/Dubai','first_scheduled_date':'2026-09-27','scope':'Weekly research and action recommendations only; no order execution or daily monitoring'},indent=2))
(r/'README.md').write_text('''# Independent investment review\n\nOpen **Investment_Review.html** for the complete reading experience: 23 tabs, including all 16 original research tabs, now clearly marked as archived.\n\n- INVESTMENT_COMMITTEE_REVIEW.md: answer-first memo and limitations.\n- WEEKLY_INVESTMENT_POLICY.md: revised weekly evidence and risk policy.\n- agents/01–06: six separate specialist reviews with sources.\n- agents/01_universe_497_diagnostics.csv: all497 corrected mechanical diagnostics, explicitly not an approved ranking.\n- data/universe_data_ledger_497.csv: dates, internal arithmetic and external-verification status.\n- agents/02_market_data.json and04_underwriting.json:14-company validation and underwriting notes.\n- data/risk_audit.json and risk_sensitivity.csv: reproduced risk results and assumptions.\n- data/dashboard_validation.json: all23 tabs rendered;14 dossiers;497-row search; interactive stress controls; mobile layout check.\n- data/source_manifest.json and source_integrity_check.json: hashes verify the original67 source files were preserved.\n- data/automation_status.json: confirmed weekly research schedule.\n\nSource snapshot:24 September2026 US close. Review date:26 September2026 Dubai. Later issuer/product page access is distinguished in the source reports. Original raw data bundle is retained separately in the workspace; this audit package does not duplicate it.\n\nThe generic data-quality skill returned false-positive allocation totals from code and repeated tables. These were not adopted as financial findings; exact stored holdings were used instead. Internal quote arithmetic is not independent feed verification. No broker access or trades occurred.\n''',encoding='utf-8')
print({'original_source_files_checked':len(manifest),'changed':changed})
