from pathlib import Path
p=Path('review/build_dashboard.py');s=p.read_text(encoding='utf-8')
s=s.replace("'underwriting':underwriting,", "'underwriting':underwriting,\n    'deepMemo':md((ROOT/'DEEP_DATA_AUDIT.md').read_text(encoding='utf-8')),\n    'deepReports':[{'name':f.stem.replace('_',' '),'html':md(f.read_text(encoding='utf-8'))} for f in sorted((ROOT/'deep_audit').glob('0[1-4]_*audit.md'))]+[{'name':'04 closure review','html':md((ROOT/'deep_audit/04_closure_review.md').read_text(encoding='utf-8'))}],\n    'filingRows':read_json(ROOT/'deep_audit/01_filing_ledger.json')['rows'],\n    'regime':read_json(ROOT/'deep_audit/reports/03_druckenmiller_readiness.json'),")
s=s.replace("'repairs','committee']);", "'repairs','committee','deepaudit','sourcegate']);")
s=s.replace("['review','Decision brief'],", "['review','Decision brief'],['deepaudit','Three deep data audits'],['sourcegate','Sources & regime gates'],")
s=s.replace("['committee','Six independent reviews']", "['committee','Original six reviews']")
s=s.replace("['14 / 14','Targeted earnings checks','Primary-source headline checks, with important accounting qualifications.']", "['3','Additional deep data audits','Filing tables, market/forecast data, and historical lineage; plus a closing challenge.']")
s=s.replace("<div class=\"controls\" style=\"margin-top:18px\">", "<div class=\"callout\"><b>Deep audit update:</b> 14 closes externally corroborated; 12 missing finalist prices and benchmark repaired; 426 stock gaps remain. Material cash-flow definitions corrected. <a href=\"#\" onclick=\"go('deepaudit');return false\">Read the new evidence</a></div><div class=\"controls\" style=\"margin-top:18px\">")
s=s.replace('Reported earnings checks passed with qualifications. Exact exchange closes, consensus definitions and investment values remain unverified. All prices below are supplied 24 September snapshots, not order prices.', 'All 14 September 24 closes are externally corroborated; NVDA and MSFT also match authenticated FMP responses. Original forecast vintages and investment values remain unresolved. These are historical snapshots, not order prices.')
s=s.replace('<div class="callout">NVIDIA:', '<div class="callout"><b>New filing corrections:</b> NVDA TTM conventional FCF $127.006bn; MSFT FY2026 $66.987bn. Airbnb Q2 FCF $1.253bn supports the rounded $1.3bn/35% claim. Detailed source/definition checks are in Three deep data audits.</div><div class="callout">NVIDIA:')
s=s.replace('Headline checked; underwriting incomplete', 'Close corroborated; underwriting incomplete')
s=s.replace('No approved entry price or target weight. Exact price and consensus independently unverified.', 'No approved entry price or target weight. Snapshot close corroborated; original consensus vintage unresolved. Earlier dossier accounting ambiguities are superseded by the deep filing audit.')
s=s.replace('All saved quote dates are 24 September 2026. Internal price/EPS/P-E checks reconcile where fields are present. No row is certified as a second-source price or consensus forecast.', 'All saved quote dates are 24 September 2026. Fourteen closing prices now have external corroboration; full exchange-feed history and original consensus vintages remain uncertified.')
s=s.replace('<th>External consensus</th>', '<th>Price evidence</th><th>Forecast evidence</th>')
s=s.replace('<td class="warn">Unverified</td>', '<td>${safe(x.quote_external_status)}</td><td class="warn">${safe(x.consensus_external_status)}</td>')
s=s.replace('Six specialist reviews. One accountable synthesis.', 'Six original reviews, followed by three deeper data audits.')
s=s.replace("<p><a href=\"INVESTMENT_COMMITTEE_REVIEW.md\"", "<div class=\"callout\">These first-pass reports are preserved. Their earlier price-verification gaps and Airbnb ambiguity are superseded by the Three deep data audits tab. Nine specialist agents contributed overall; shared data and model family limit independence.</div><p><a href=\"INVESTMENT_COMMITTEE_REVIEW.md\"")
newjs=r'''
R.deepaudit=()=>{
 $('#app').innerHTML=title('THREE PARALLEL DATA AUDITS · 26 SEP 2026','Trace the number to its source.','Targeted six-company filing audit · 14-name market audit · 497-company historical lineage audit. Evidence depth improved; investment approval remains withheld.')+
 `<div class="tally"><div><b>33</b><strong>Filing / provider field checks</strong><p class="sm mute">Exact periods, formulas, source locators and quarantines.</p></div><div><b>154</b><strong>Market field observations</strong><p class="sm mute">14 candidates; forecast vintage remains unresolved.</p></div><div><b>593</b><strong>Cached documents inspected</strong><p class="sm mute">Coverage and truncation audited across the cache.</p></div><div><b>12 + 1</b><strong>Missing-day observations repaired</strong><p class="sm mute">Twelve finalists plus benchmark; 426 stock gaps remain.</p></div></div>
 <p><a href="DEEP_DATA_AUDIT.md" download>Download synthesis</a> · <a href="deep_audit/01_filing_ledger.csv" download>Filing evidence CSV</a> · <a href="deep_audit/02_market_ledger.csv" download>Market evidence CSV</a> · <a href="deep_audit/03_document_ledger.csv" download>593-document ledger</a> · <a href="deep_audit/03_finalist_repair_impact.json" download>Before / after calculations</a></p>
 ${REVIEW.deepMemo}
 <h2>Exact field evidence</h2><div class="controls"><input id="findFact" type="search" placeholder="Search ticker, field or status" aria-label="Search filing evidence"><span id="factCount"></span></div><div class="scroll"><table><thead><tr><th>Stock / field</th><th>Period / basis</th><th>Reconciled value / unit</th><th>Formula / locator</th><th>Status</th></tr></thead><tbody id="factRows"></tbody></table></div>
 <h2>Read each audit and the closing challenge</h2>${REVIEW.deepReports.map(x=>`<details><summary>${safe(x.name)}</summary>${x.html}</details>`).join('')}`;
 const fill=()=>{const q=$('#findFact').value.toLowerCase();const rows=REVIEW.filingRows.filter(x=>[x.ticker,x.field,x.status].join(' ').toLowerCase().includes(q));$('#factCount').textContent=rows.length+' field checks';$('#factRows').innerHTML=rows.map(x=>`<tr><td><b>${safe(x.ticker)}</b><br>${safe(x.field)}</td><td>${safe(x.period)}<br><span class="sm mute">${safe(x.basis)}</span></td><td>${safe(x.primary_or_derived_value??'Unknown')}<br>${safe(x.units)}</td><td>${safe(x.formula)}<br><span class="sm mute">${safe(x.locator)}</span></td><td class="${x.quarantine?'bad':'mute'}">${safe(x.status)}</td></tr>`).join('');};$('#findFact').oninput=fill;fill();
};
R.sourcegate=()=>{
 $('#app').innerHTML=title('ACTUAL ACCESS · SHARED LINEAGE · MISSING INPUTS','Provider access and regime readiness','Source documentation, actual observations, independent extraction and investment judgment are different evidence layers.')+
 `<div class="grid"><div class="card hi"><h3>FMP: actual responses acquired</h3><p>NVDA / MSFT September 24 closes and three annual cash-flow rows each. The other 12 price requests returned 402. Bundled AAPL samples were rejected by symbol/date checks.</p><p class="sm mute">NVIDIA full JSON retained. Microsoft selected fields transcribed from Raw UI, explicitly labeled. No credential is included.</p></div><div class="card"><h3>Financial Datasets: documentation only</h3><p>The linked plugin showed Install and no authenticated connector was callable. Provenance documents name Databento prices and SEC filing extraction; no portfolio figures were validated through this provider.</p><p><a href="https://docs.financialdatasets.ai/data-provenance" target="_blank" rel="noopener">Provider provenance</a></p></div></div>
 <p><a href="deep_audit/00_provider_access_ledger.json" download>Provider access and capture ledger</a> · <a href="deep_audit/raw_filing/manifest.json" download>Archived filing hashes</a> · <a href="deep_audit/reports/03_druckenmiller_readiness.json" download>Actual regime runs and readiness</a></p>
 <h2>Requested Druckenmiller framework: incomplete</h2><div class="scroll"><table><thead><tr><th>Required input</th><th>Actual result</th><th>Underlying date</th><th>Status</th></tr></thead><tbody>${REVIEW.regime.required_reports.map(x=>`<tr><td>${safe(x.skill)}</td><td>${x.score!=null?safe(x.score)+'/100':'Unavailable'}</td><td>${safe(x.data_date||'None')}</td><td>${safe(x.status)}</td></tr>`).join('')}</tbody></table></div>
 <div class="callout"><b>Combined conviction and allocation withheld.</b> Three required reports could not run. The two generated signals share TraderMonty lineage and are uncalibrated heuristics. The full lineage audit documents unsafe schema defaults, stale-data checks and directional scoring issues. No generic concentration rule overrides your risk tolerance.</div>
 <h2>Weekly release requirements</h2><p>Filing/accounting review → market/forecast review → historical/transformation review. Material failures block new purchases. Require explicit source dates, fiscal definitions, raw hashes and before/after risk effects; preserve conflicts instead of averaging them away.</p><p>Existing holdings require their own thesis and risk assessment. A data outage does not automatically mean sell. Sunday 18:00 Dubai research continues; no daily monitoring or execution is active.</p>`;
};
'''
s=s.replace('const previousGo=go;',newjs+'\nconst previousGo=go;')
s=s.replace("'new_tabs':7", "'new_tabs':9")
p.write_text(s,encoding='utf-8')
print('Added two audit tabs and updated current evidence; original sixteen tabs preserved.')
