"""r3_literature_records.py - curated literature records for the R3 evidence base (imported by r3_curated_sources.py).

Verification codes:
  VERIFIED-R3  : R3 checked the number/claim in the primary source (PDF text, publisher/Crossref abstract) on 2026-09-26
  VERIFIED-SUB : an R3 research sub-agent checked it in the primary source (PDF/publisher page; citation metadata via Crossref)
  PARTLY / SECONDARY : some numbers only from working-paper versions or reputable secondary summaries (stated in the row)
  "Our data" items are R3's own computations on the Kenneth French Data Library (v4/data/r3_factor_*.csv, r3_largecap_longonly_stats.csv).
Paraphrased throughout (no long quotations).
"""

LIT = [
    dict(paper="Returns to Buying Winners and Selling Losers", authors="Jegadeesh & Titman", journal="JF 48(1):65-91", year=1993,
         sample="NYSE/AMEX, 1965-1989",
         key_finding="6-month/6-month relative-strength strategy earns ~12.0%/yr compounded (~1%/month); 12m/3m best at 1.31%/month; cumulative gain peaks ~9.5% at month 12 and partly reverses (~4% by month 36).",
         decay_caveats="Persisted in the 1990s (JT 2001, JF 56(2)). Our data: UMD 9.9%/yr in JT's sample vs 4.7%/yr after publication (-53%). Crash-prone (see Daniel & Moskowitz).",
         doi_url="https://doi.org/10.1111/j.1540-6261.1993.tb04702.x", verification="VERIFIED-SUB; decay = our data"),
    dict(paper="Value and Momentum Everywhere", authors="Asness, Moskowitz & Pedersen", journal="JF 68(3):929-985", year=2013,
         sample="8 markets/asset classes, 1972-2011 (US: ~724 liquid large caps)",
         key_finding="Value and momentum premia in every asset class; value-momentum correlation about -0.6 within stock markets; global 50/50 value+momentum combination Sharpe 1.45.",
         decay_caveats="Standalone Sharpe ratios slightly lower in 1992-2011 than 1972-1991; gross of costs; value then suffered its 2007-2020 drawdown.",
         doi_url="https://doi.org/10.1111/jofi.12021", verification="VERIFIED-SUB"),
    dict(paper="Momentum Crashes", authors="Daniel & Moskowitz", journal="JFE 122(2):221-247", year=2016,
         sample="US 1927-2013 + international equities and other asset classes",
         key_finding="Crashes happen in 'panic' states (after market falls, high volatility) when markets rebound: Mar-May 2009 losers +163% vs winners +8%; Jul-Aug 1932 losers +232% vs winners +32%. Dynamic weighting roughly doubles alpha and Sharpe.",
         decay_caveats="Constant-volatility scaling is an alternative fix (Barroso & Santa-Clara 2015, JFE 116(1)). Our data: UMD -49% in Mar-May 2009; worst drawdown -78% (1932-39).",
         doi_url="https://doi.org/10.1016/j.jfineco.2015.12.002", verification="VERIFIED-SUB; our data"),
    dict(paper="The Cross-Section of Expected Stock Returns", authors="Fama & French", journal="JF 47(2):427-465", year=1992,
         sample="NYSE/AMEX/NASDAQ nonfinancials, 1963-1990",
         key_finding="Beta has no reliable relation to average returns; B/M decile returns rise from 0.30% to 1.83%/month (spread 1.53%/month); size and B/M absorb E/P and leverage effects.",
         decay_caveats="Our data: HML 5.1%/yr in FF's sample vs 2.2%/yr after publication (-57%). Fama & French (2021, RAPS 11(1):105-121): value premium much lower in the second half of 1963-2019, but too volatile to reject equal expected premia.",
         doi_url="https://doi.org/10.1111/j.1540-6261.1992.tb04398.x", verification="VERIFIED-SUB; decay = our data"),
    dict(paper="Common Risk Factors in the Returns on Stocks and Bonds", authors="Fama & French", journal="JFE 33(1):3-56", year=1993,
         sample="US 1963-07 to 1991-12",
         key_finding="Three-factor model; HML 0.40%/month (t 2.91), SMB 0.27%/month (t 1.73).",
         decay_caveats="Size premium weak since (our data: SMB +2.2%/yr, t 1.7, 1963-2026; -0.8%/yr since 2010).",
         doi_url="https://doi.org/10.1016/0304-405X(93)90023-5", verification="VERIFIED-SUB"),
    dict(paper="A Five-Factor Asset Pricing Model", authors="Fama & French", journal="JFE 116(1):1-22", year=2015,
         sample="US 1963-07 to 2013-12",
         key_finding="Adds profitability (RMW) and investment (CMA); explains 71-94% of the cross-section variance of expected returns for test portfolios; HML redundant in this sample; HML only 0.21%/month (t 1.69) among big stocks vs 0.53% among small.",
         decay_caveats="Our data after publication (2015-05 to 2026-07): RMW 2.7%/yr (t 1.1; -15% vs in-sample), CMA -0.3%/yr (-108%).",
         doi_url="https://doi.org/10.1016/j.jfineco.2014.10.010", verification="VERIFIED-SUB; decay = our data"),
    dict(paper="The Other Side of Value: The Gross Profitability Premium", authors="Novy-Marx", journal="JFE 108(1):1-28", year=2013,
         sample="US nonfinancials 1963-07 to 2010-12",
         key_finding="Gross profits/assets predicts returns about as well as B/M: value-weighted quintile spread 0.31%/month (t 2.49), FF3 alpha 0.52%/month (t 4.49); correlation with value -0.57, so combining improves both.",
         decay_caveats="Large caps alone: 0.26%/month (t 1.88), but large-cap profitability+value earns 0.62%/month (Sharpe 0.74). French's RMW uses operating, not gross, profitability.",
         doi_url="https://doi.org/10.1016/j.jfineco.2013.01.003", verification="VERIFIED-SUB"),
    dict(paper="Quality Minus Junk", authors="Asness, Frazzini & Pedersen", journal="Review of Accounting Studies 24(1):34-112", year=2019,
         sample="US 1957-2016; 24 countries 1989-2016 (54,616 stocks)",
         key_finding="Quality (profitable, growing, safe, well-managed) earns significant risk-adjusted returns: US QMJ alphas 39-60 bp/month (t 5.4-10.0), global 51-61 bp; quality stocks trade at only moderately higher prices.",
         decay_caveats="Raw top-minus-bottom decile spread only 42-52 bp/month (t ~2.5); much of the alpha comes from QMJ's low/negative beta. Authors are AQR-affiliated.",
         doi_url="https://doi.org/10.1007/s11142-018-9470-2", verification="VERIFIED-SUB"),
    dict(paper="Asset Growth and the Cross-Section of Stock Returns", authors="Cooper, Gulen & Schill", journal="JF 63(4):1609-1651", year=2008,
         sample="US nonfinancials 1968-2003",
         key_finding="Low-minus-high total asset growth decile: ~20%/yr equal-weighted raw (~26% vs 6%), ~13%/yr value-weighted raw, ~8.4%/yr value-weighted risk-adjusted; effect holds among large caps.",
         decay_caveats="Now embedded in CMA/q-factor investment. Our data: CMA 5.5%/yr in CGS's sample vs 0.6%/yr after 2008 (-90%); -0.7%/yr since 2015.",
         doi_url="https://doi.org/10.1111/j.1540-6261.2008.01370.x", verification="PARTLY (numbers from SSRN WP/secondary; JF abstract verified)"),
    dict(paper="Share Issuance and Cross-sectional Returns", authors="Pontiff & Woodgate", journal="JF 63(2):921-945", year=2008,
         sample="US, post-1970 (with an earlier comparison period)",
         key_finding="Post-1970, net share issuance predicts returns (negatively) more significantly than size, B/M or momentum; no significant predictive power in the earlier period for most horizons. Chen & Zimmermann replication 0.58%/month (t 4.9).",
         decay_caveats="Holds internationally (McLean, Pontiff & Watanabe 2009, JFE 94(1)). Our data: big-cap net repurchasers +1.5%/yr active 1963-2026, only +0.1%/yr since 2010.",
         doi_url="https://doi.org/10.1111/j.1540-6261.2008.01335.x", verification="VERIFIED-SUB (start of pre-1970 period unverified)"),
    dict(paper="Market Reactions to Tangible and Intangible Information", authors="Daniel & Titman", journal="JF 61(4):1605-1643", year=2006,
         sample="US",
         key_finding="B/M predicts returns because it proxies for the 'intangible' (non-fundamental) part of past returns; a composite equity-issuance measure independently forecasts returns negatively.",
         decay_caveats="Numeric results not checked by R3.",
         doi_url="https://doi.org/10.1111/j.1540-6261.2006.00884.x", verification="VERIFIED-SUB (abstract level)"),
    dict(paper="Do Stock Prices Fully Reflect Information in Accruals and Cash Flows about Future Earnings?", authors="Sloan", journal="The Accounting Review 71(3):289-315", year=1996,
         sample="40,679 NYSE/AMEX firm-years, 1962-1991",
         key_finding="Accruals are less persistent than cash flows, but prices act as if investors fixate on earnings; a low-minus-high accrual hedge earns 10.4% size-adjusted in year 1 (t 4.7), positive in 28 of 30 years.",
         decay_caveats="Green, Hand & Soliman (2011, Mgmt Sci 57(5):797-816): the hedge return decayed until it was no longer reliably positive. Our data: big-cap low-accrual quintile +1.9%/yr active 1963-2026, +2.4%/yr since 2010 (t 1.6).",
         doi_url="https://doi.org/10.2308/tar-9608042309", verification="VERIFIED-SUB"),
    dict(paper="Post-Earnings-Announcement Drift: Delayed Price Response or Risk Premium?", authors="Bernard & Thomas", journal="JAR 27 (Suppl.):1-36", year=1989,
         sample="NYSE/AMEX quarterly announcements, 1974-1986",
         key_finding="Prices keep drifting in the direction of the earnings surprise for ~60 trading days: extreme SUE deciles about +/-2% each (~4% long-short per quarter, ~18% annualized).",
         decay_caveats="Chordia, Goyal, Sadka, Sadka & Shivakumar (2009, FAJ 65(4)): drift 0.04%/month in the most liquid stocks vs 2.43% in the least, and costs absorb 70-100% of paper profits.",
         doi_url="https://doi.org/10.2307/2491062", verification="SECONDARY for numbers (paper behind JSTOR)"),
    dict(paper="Rest in Peace Post-Earnings Announcement Drift", authors="Martineau", journal="Critical Finance Review 11(3-4):613-646", year=2022,
         sample="US, recent decades",
         key_finding="Earnings surprises are now fully priced on the announcement day: the drift has been insignificant for large stocks since ~2006 and more recently for microcaps too.",
         decay_caveats="Text-based surprises still show drift (Meursault, Liang, Routledge & Scanlon 2023, JFQA 58(6):2299-2326: 1-yr drift 8.0% text-based vs 4.6% classic SUE in 2010-2019, working-paper figures).",
         doi_url="https://doi.org/10.1561/104.00000122", verification="VERIFIED-SUB"),
    dict(paper="Betting Against Beta", authors="Frazzini & Pedersen", journal="JFE 111(1):1-25", year=2014,
         sample="US 1926-2012 + 19 international markets, Treasuries, credit, futures",
         key_finding="Long leveraged low-beta / short high-beta (BAB) has US Sharpe 0.78 and FF3 alpha 0.73%/month (t 7.4); the security market line is flatter than CAPM predicts in 18 of 19 markets.",
         decay_caveats="Novy-Marx & Velikov (2022, JFE 143(1):80-106): BAB's construction effectively equal-weights and loads on tiny stocks; its return is explained by profitability/investment tilts. Our data: big-cap low-beta quintile -0.6%/yr raw active (beta 0.70), CAPM alpha +1.4%/yr (t 1.7), 1963-2026.",
         doi_url="https://doi.org/10.1016/j.jfineco.2013.10.005", verification="VERIFIED-SUB; our data"),
    dict(paper="The Cross-Section of Volatility and Expected Returns", authors="Ang, Hodrick, Xing & Zhang", journal="JF 61(1):259-299", year=2006,
         sample="US 1963-07 to 2000-12",
         key_finding="Stocks with high idiosyncratic volatility (relative to FF3) earn very low returns: top-minus-bottom quintile -1.06%/month (value-weighted).",
         decay_caveats="Bali & Cakici (2008, JFQA 43(1):29-58): not robust to weighting, breakpoints, data frequency and size/price/liquidity screens. Our data: big-cap low-variance quintile -1.0%/yr raw active (beta 0.66), CAPM alpha +1.3%/yr (t 1.4), 1963-2026.",
         doi_url="https://doi.org/10.1111/j.1540-6261.2006.00836.x", verification="VERIFIED-SUB; our data"),
    dict(paper="Does Academic Research Destroy Stock Return Predictability?", authors="McLean & Pontiff", journal="JF 71(1):5-32", year=2016,
         sample="97 published cross-sectional return predictors",
         key_finding="Predictor portfolio returns are 26% lower out-of-sample (upper bound on data mining) and 58% lower after publication; 32% is attributed to publication-informed trading; bigger declines for predictors with higher in-sample returns.",
         decay_caveats="Implies keeping ~40% of in-sample premia for published signals. Our French check: -53% (momentum), -57% (value).",
         doi_url="https://doi.org/10.1111/jofi.12365", verification="VERIFIED-R3 (Crossref abstract)"),
    dict(paper="...and the Cross-Section of Expected Returns", authors="Harvey, Liu & Zhu", journal="RFS 29(1):5-68", year=2016,
         sample="316 factors from 313 papers",
         key_finding="Once you account for how many factors have been tried, a newly proposed factor needs t > 3.0; most claimed research findings in financial economics are likely false.",
         decay_caveats="Companion Harvey & Liu (2015, JPM 42(1):13-28): the Sharpe-ratio haircut is nonlinear; the 50% rule of thumb is too lenient below Sharpe 0.4 and too harsh above 1.0.",
         doi_url="https://doi.org/10.1093/rfs/hhv059", verification="VERIFIED-SUB; HL(2015) VERIFIED-R3"),
    dict(paper="Replicating Anomalies", authors="Hou, Xue & Zhang", journal="RFS 33(5):2019-2133", year=2020,
         sample="452 anomalies, US",
         key_finding="With microcaps mitigated (NYSE breakpoints, value-weighted returns), 65% fail |t| >= 1.96 (including 96% of the trading-frictions category) and 82% fail t >= 2.78; replicated anomalies are much smaller than originally reported.",
         decay_caveats="Supports a large-cap, value-weighted implementation of only the robust families, with shrunken premia.",
         doi_url="https://doi.org/10.1093/rfs/hhy131", verification="VERIFIED-R3 (Crossref abstract)"),
    dict(paper="Is There a Replication Crisis in Finance?", authors="Jensen, Kelly & Pedersen", journal="JF 78(5):2465-2518", year=2023,
         sample="153 factors, 93 countries",
         key_finding="With a Bayesian framework, most factors replicate (82.4% in the US), cluster into 13 themes, work out-of-sample internationally, and their evidence is strengthened (not weakened) by the large number of factors.",
         decay_caveats="Average alpha 0.49%/month in-sample vs 0.26% after the original samples (-47%): decay, not disappearance.",
         doi_url="https://doi.org/10.1111/jofi.13249", verification="VERIFIED-R3 (abstract); 82.4% and alpha figures VERIFIED-SUB"),
    dict(paper="Open Source Cross-Sectional Asset Pricing", authors="Chen & Zimmermann", journal="Critical Finance Review 11(2):207-264", year=2022,
         sample="319 characteristics",
         key_finding="98% of the 161 clearly significant predictors reproduce with t > 1.96; reproduced vs original t-stats slope 0.88.",
         decay_caveats="Reproduction is in-sample; it says nothing about post-publication returns.",
         doi_url="https://doi.org/10.1561/104.00000112", verification="VERIFIED-SUB"),
    dict(paper="How Do Factor Premia Vary Over Time? A Century of Evidence", authors="Ilmanen, Israel, Lee, Moskowitz & Thapar", journal="Journal of Investment Management 19(4)", year=2021,
         sample="Value, momentum, carry, defensive across 6 asset classes, ~1926-2020",
         key_finding="Pooled t-stats 5.1 (value) to >6.6 (defensive); multifactor Sharpe 1.46; out-of-sample Sharpe 49% below original-sample for value but only 18% lower for the multifactor combination; little evidence of arbitrage-driven decay.",
         decay_caveats="AQR authors; the long-short, multi-asset setting differs from large-cap long-only equities.",
         doi_url="https://doi.org/10.2139/ssrn.3400998", verification="VERIFIED-SUB (forthcoming draft)"),
    dict(paper="Is (Systematic) Value Investing Dead?", authors="Israel, Laursen & Richardson", journal="JPM 47(2):38-62", year=2021,
         sample="US equities, focus on the 2018-2020 value drawdown",
         key_finding="Value's recent underperformance came mainly from a widening gap between prices and fundamentals (valuation spreads), not from value's fundamentals failing.",
         decay_caveats="Decomposition numbers not checked.",
         doi_url="https://doi.org/10.3905/jpm.2020.1.194", verification="VERIFIED-SUB (abstract level)"),
    dict(paper="Reports of Value's Death May Be Greatly Exaggerated", authors="Arnott, Harvey, Kalesnik & Linnainmaa", journal="FAJ 77(1):44-67", year=2021,
         sample="US, value 2007-2020",
         key_finding="HML fell ~55% from 2007 to mid-2020; the change in relative valuations explains the entire drawdown; capitalising intangibles improves value.",
         decay_caveats="Our data: HML -57.8% peak-to-trough (2006-12 to 2020-09), then +68.5% from 2020-10 to 2022-12.",
         doi_url="https://doi.org/10.1080/0015198X.2020.1842704", verification="VERIFIED-SUB; our data"),
    dict(paper="The Role of Shorting, Firm Size, and Time on Market Anomalies", authors="Israel & Moskowitz", journal="JFE 108(2):275-301", year=2013,
         sample="86 years US + ~40 years international equities and asset classes",
         key_finding="The long side supplies ~60% of value and ~half of momentum profits (almost all of size); the value premium falls with firm size and is weak among the largest stocks; momentum has no reliable size relation; variation over time looks like chance.",
         decay_caveats="Consistent with our large-cap long-only capture of ~45-54% of the all-cap combo premium.",
         doi_url="https://doi.org/10.1016/j.jfineco.2012.11.005", verification="VERIFIED-SUB"),
    dict(paper="When Equity Factors Drop Their Shorts", authors="Blitz, Baltussen & van Vliet", journal="FAJ 76(4):73-99", year=2020,
         sample="US and international equities",
         key_finding="Both legs carry premia, but most added value comes from the long legs, and the shorts are largely subsumed by the longs, in large and small caps alike.",
         decay_caveats="Magnitudes not checked.",
         doi_url="https://doi.org/10.1080/0015198X.2020.1779560", verification="VERIFIED-SUB (abstract level)"),
    dict(paper="A Taxonomy of Anomalies and Their Trading Costs", authors="Novy-Marx & Velikov", journal="RFS 29(1):104-147", year=2016,
         sample="US anomalies",
         key_finding="Most anomalies with <50% monthly turnover keep significant net spreads with cost mitigation (buy/hold spreads); few high-turnover ones do; size, value and profitability have the largest capacity.",
         decay_caveats="Institutional live-trade costs are much lower (Frazzini, Israel & Moskowitz 2018 WP 'Trading Costs', SSRN 3229719); a small investor's costs sit between the two.",
         doi_url="https://doi.org/10.1093/rfs/hhv063", verification="VERIFIED-SUB"),
    dict(paper="Long-Only Style Investing: Don't Just Mix, Integrate", authors="Fitzgibbons, Friedman, Pomorski & Serban", journal="Journal of Investing 26(4):153-164", year=2017,
         sample="Long-only style portfolios",
         key_finding="Integrating styles in a single portfolio beats a mix of stand-alone style sleeves (higher return and IR) by avoiding stocks with offsetting exposures.",
         decay_caveats="AQR authors.",
         doi_url="https://www.aqr.com/Insights/Research/White-Papers/Long-Only-Style-Investing", verification="VERIFIED-R3 (abstract via journal/AQR pages)"),
    dict(paper="Stocks for the Long Run? Evidence from a Broad Sample of Developed Markets", authors="Anarkulova, Cederburg & O'Doherty", journal="JFE 143(1):409-433", year=2022,
         sample="39 developed markets, 1841-2019 (bootstrap)",
         key_finding="A diversified investor with a 30-year horizon has a 12% chance of losing to inflation.",
         decay_caveats="Counterweight to US-only 'stocks always win over 20 years' evidence.",
         doi_url="https://doi.org/10.1016/j.jfineco.2021.06.040", verification="VERIFIED-R3 (abstract)"),
]
