/* v4 tabs — injected before `tabs();R[cur]();` in the benchmark dashboard. Adds, never removes. Data: D4V. */
const D4V=__DATA4__;
(function(){
const L=TABS.find(t=>t[0]==='cv'); if(L) L[1]='v3 · Conviction portfolio (superseded)';
TABS.unshift(['v4v','★ v4 Verdict & portfolio'],['v4dos','v4 · Stock dossiers'],['v4ev','v4 · Evidence (backtest)'],['v4risk','v4 · Risk & allocation'],['v4impl','v4 · Implementation & weekly review'],['v4rank','v4 · Ranking (all ~500)'],['v4aud','v4 · What was wrong with v3'],['v4meth','v4 · Method & data lineage'],['v4grade','v4 · Independent audit scores'],['v4recon','v4 · Reconciliation with Codex v005']);
cur='v4v';
})();
const V4=D4V;
const f1=(x,d=1)=>x==null?'–':Number(x).toFixed(d);
const pp=(x,d=0)=>x==null?'–':(x*100).toFixed(d)+'%';
const spp=(x,d=1)=>x==null?'–':(x>0?'+':'')+(x*100).toFixed(d)+'%';
const pass=b=>b?'<span class="ok">Pass</span>':'<span class="bad">Fail</span>';
const tierTag4=v=>{const m={'INCLUDE':'tA','INCLUDE-SMALL':'tB','WATCH':'tC','REJECT':'tC'};return v?`<span class="tag ${m[v]||'tC'}">${esc(v)}</span>`:''};
/* ---------- charts (SVG, drawn to one scale per axis, theme tokens) ---------- */
function lineChart(d,o={}){
 const W=900,H=o.h||320,Lm=58,Rm=110,T=14,B=30,log=!!o.log;const xs=d.x.map(s=>new Date(s).getTime());
 const all=d.series.flatMap(s=>s.v.filter(v=>v!=null&&(!log||v>0)));if(!all.length)return'';
 let y0=Math.min(...all),y1=Math.max(...all);if(o.zero&&!log)y0=Math.min(0,y0);
 const fy=v=>log?Math.log(v):v;const Y0=fy(y0),Y1=fy(y1),pad=(Y1-Y0)*0.06||1;const ya=Y0-pad,yb=Y1+pad;
 const X=t=>Lm+(t-xs[0])/(xs[xs.length-1]-xs[0])*(W-Lm-Rm),Y=v=>T+(1-(fy(v)-ya)/(yb-ya))*(H-T-B);
 let s='';
 let ticks=[];if(log){for(const m of [0.25,0.5,1,2,3,4,5,6,8,10,15,20]){if(m>=y0*0.95&&m<=y1*1.05)ticks.push(m)}}else{const st=o.step||niceStep(y1-y0);for(let v=Math.ceil(y0/st)*st;v<=y1+1e-9;v+=st)ticks.push(v)}
 ticks.forEach(v=>{s+=`<line x1="${Lm}" x2="${W-Rm}" y1="${Y(v)}" y2="${Y(v)}" stroke="var(--line)"/><text x="${Lm-8}" y="${Y(v)+4}" text-anchor="end">${o.yfmt?o.yfmt(v):f1(v,2)}</text>`});
 const y0d=new Date(xs[0]).getFullYear(),y1d=new Date(xs[xs.length-1]).getFullYear();const every=Math.max(1,Math.ceil((y1d-y0d)/10));
 for(let yr=y0d+1;yr<=y1d;yr+=every){const t=new Date(yr+'-01-01').getTime();if(t<xs[0])continue;s+=`<line x1="${X(t)}" x2="${X(t)}" y1="${T}" y2="${H-B}" stroke="var(--line)" stroke-dasharray="2 4"/><text x="${X(t)}" y="${H-B+16}" text-anchor="middle">${yr}</text>`}
 const lab=[];d.series.forEach(se=>{let p='';se.v.forEach((v,i)=>{if(v==null||(log&&v<=0))return;p+=(p?'L':'M')+X(xs[i]).toFixed(1)+' '+Y(v).toFixed(1)});
  s+=`<path d="${p}" fill="none" stroke="${se.c}" stroke-width="${se.w||2}" ${se.dash?'stroke-dasharray="5 4"':''}/>`;
  let li=se.v.length-1;while(li>0&&se.v[li]==null)li--;lab.push({y:Y(se.v[li]),t:`${se.name}${o.endfmt?' '+o.endfmt(se.v[li]):''}`,c:se.c,x:X(xs[li])})});
 lab.sort((a,b)=>a.y-b.y);for(let i=1;i<lab.length;i++)if(lab[i].y-lab[i-1].y<14)lab[i].y=lab[i-1].y+14;
 lab.forEach(l=>{s+=`<circle cx="${l.x}" cy="${l.y}" r="0" fill="${l.c}"/><text x="${W-Rm+6}" y="${l.y+4}" style="fill:${l.c}">${esc(l.t)}</text>`});
 return `<svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${esc(o.aria||'line chart')}">${s}</svg>`}
function niceStep(r){const e=Math.pow(10,Math.floor(Math.log10(r/5)));const m=r/5/e;return (m<1.5?1:m<3?2:m<7?5:10)*e}
function barChart(items,o={}){
 const W=900,H=o.h||260,Lm=50,T=18,B=44,n=items.length;const vals=items.map(i=>i[1]);const lo=Math.min(0,...vals),hi=Math.max(0,...vals);const pad=(hi-lo)*0.12||0.01;
 const Y=v=>T+(1-(v-(lo-(lo<0?pad:0)))/((hi+pad)-(lo-(lo<0?pad:0))))*(H-T-B);const bw=(W-Lm-10)/n;let s='';
 const st=niceStep(hi-lo||0.01);for(let v=Math.ceil(lo/st)*st;v<=hi+pad;v+=st){s+=`<line x1="${Lm}" x2="${W-10}" y1="${Y(v)}" y2="${Y(v)}" stroke="var(--line)"/><text x="${Lm-6}" y="${Y(v)+4}" text-anchor="end">${o.fmt?o.fmt(v):f1(v)}</text>`}
 if(o.ref!=null)s+=`<line x1="${Lm}" x2="${W-10}" y1="${Y(o.ref)}" y2="${Y(o.ref)}" stroke="var(--gold)" stroke-dasharray="4 4"/><text x="${W-12}" y="${Y(o.ref)-5}" text-anchor="end" style="fill:var(--gold)">${esc(o.refLabel||'')}</text>`;
 items.forEach(([l,v,c],i)=>{const x=Lm+i*bw+bw*0.15,w=bw*0.7,y=Math.min(Y(v),Y(0)),h=Math.abs(Y(v)-Y(0));
  s+=`<rect x="${x}" y="${y}" width="${w}" height="${Math.max(h,1)}" fill="${c||(v>=0?'var(--gold)':'var(--down)')}" fill-opacity=".8"/><text x="${x+w/2}" y="${(v>=0?y-5:y+h+13)}" text-anchor="middle" style="fill:var(--ink)">${o.fmt?o.fmt(v):f1(v)}</text><text x="${x+w/2}" y="${H-B+16}" text-anchor="middle">${esc(l)}</text>`});
 if(o.xlabel)s+=`<text x="${(W+Lm)/2}" y="${H-6}" text-anchor="middle">${esc(o.xlabel)}</text>`;
 return `<svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${esc(o.aria||'bar chart')}">${s}</svg>`}
const ppr=v=>v==null?'–':(v>=0.995?'>99%':(v<0.005?'<1%':pp(v)));  /* probabilities: never a simulated 100% or 0% */
function hbars(items,o={}){const mx=o.max||Math.max(...items.map(i=>Math.abs(i[1])))||1;return '<div class="bars">'+items.map(([k,v])=>`<div><span>${esc(k)}</span><em><i style="width:${Math.max(2,Math.abs(v)/mx*100)}%"></i></em><span class="num">${o.fmt?o.fmt(v):f1(v)}</span></div>`).join('')+'</div>'}
function kvCard(title,pairs,hi){return `<div class="card${hi?' hi':''}"><h4>${esc(title)}</h4><div class="kv">${pairs.map(([a,b])=>`<span>${esc(a)}</span><b>${b}</b>`).join('')}</div></div>`}
function listCard(title,items,cls){return `<div class="card"><h4 class="${cls||''}">${esc(title)}</h4><ul class="pts">${(items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`}
function simpleTable(head,rows,numCols=[]){return `<div class="scroll"><table><thead><tr>${head.map((h,i)=>`<th class="${numCols.includes(i)?'num':''}">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td class="${numCols.includes(i)?'num':''}${typeof c==='string'&&c.length>60?' w':''}">${c??'–'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
/* ---------- tabs ---------- */
R.v4v=()=>{const H=V4.hero||{},P=V4.port||{},rows=(P.rows||[]).slice().sort((a,b)=>a.rank-b.rank);
$('#app').innerHTML=`<p class="mute sm">v4 · data to US close ${esc(V4.asof||'')} · research, not personal financial advice</p><h1>${esc(H.title||'')}</h1><p class="lede">${H.lede||''}</p>
<div class="tally">${(H.tiles||[]).map(([v,l])=>`<div><b>${v}</b><span>${esc(l)}</span></div>`).join('')}</div>
${(V4.answer||[]).length?`<div class="grid">${V4.answer.map(a=>`<div class="card"><h4>${esc(a.k)}</h4><p class="sm">${a.v}</p></div>`).join('')}</div>`:''}
${((V4.risk||{}).allocBars||[]).length?`<h2>The allocation decision at a glance</h2><p class="mute sm">Base-case market scenario (6% a year), 20,000 simulated paths, stock satellite assumed to have no edge. Bars share one 0–100% scale.</p><div class="grid">${V4.risk.allocBars.map(([t,it])=>`<div class="card"><h4>${esc(t)}</h4>${hbars(it,{max:1,fmt:ppr})}</div>`).join('')}</div>`:''}
${rows.length?`<h2>The portfolio, ranked and weighted</h2><p class="mute">${P.note||''}</p><div class="scroll"><table id="v4pt"></table></div>`:`<div class="callout"><b>Portfolio pending.</b> It is built only after the point-in-time backtest, the deep data audits and the company diligence are complete. The live status of every audit loop is in the “Independent audit scores” tab.</div>`}
${P.index_fill?`<p class="sm"><b>${pp(P.index_fill,0)} of the stock sleeve is held in the S&amp;P 500 index fund.</b> With ${rows.length} names the name and sector caps cannot absorb more, and the index is the neutral holding because the model shows no edge.</p>`:(P.cash?`<p class="sm mute">Cash / unallocated: ${pp(P.cash,1)} (constraints would otherwise be breached).</p>`:'')}
${rows.length?`<div class="card"><h4>How to read the table</h4><ul class="pts sm"><li><b>Weight</b>: share of the stock sleeve (not of your whole portfolio). Full-conviction names get 3–10%, half-conviction names 1.5–5%.</li><li><b>Diligence</b>: INCLUDE = full conviction; INCLUDE-SMALL = investable with a named reservation, held at half weight.</li><li><b>Model score</b>: 0–100 rank on quality, value, momentum and earnings surprise. It did not predict returns in the 2012–26 test, so it is a starting point, not a forecast.</li><li><b>NTM P/E</b>: price ÷ the next twelve months of expected earnings per share (for property REITs, price ÷ funds from operations). Lower means cheaper per dollar of profit.</li><li><b>Base rate, similar stocks</b>: how often stocks in the same score and volatility band rose, or beat the index, over 12 months in 2011–25. It describes the group, not a forecast for the stock, and barely varies because the score did not predict returns.</li><li><b>3-yr bear / base / bull</b>: yearly return if the valuation returns to the low, middle or high of the company's own history.</li><li><b>Exit if…</b>: the first pre-written condition that would mean the case is broken.</li></ul></div>`:''}
${(V4.glossary||[]).length?`<details class="card" style="margin-top:14px"><summary><b>Plain-English glossary</b> <span class="mute sm">(${V4.glossary.length} terms: t-stat, tracking error, reverse DCF and the rest)</span></summary><ul class="pts sm">${V4.glossary.map(g=>`<li><b>${esc(g[0])}:</b> ${esc(g[1])}</li>`).join('')}</ul></details>`:''}
<div class="grid">${P.stats?kvCard('Portfolio vs S&P 500',P.stats,true):''}${(P.constraints||[]).length?`<div class="card"><h4>Constraints, verified after solving</h4>${simpleTable(['Constraint','Limit','Actual','Result'],P.constraints.map(c=>[esc(c[0]),pp(c[1],1),pp(c[2],2),pass(c[3])]),[1,2])}</div>`:''}
${(P.sectors||[]).length?`<div class="card"><h4>Sector weights vs S&amp;P 500</h4>${simpleTable(['Sector','Portfolio','S&P 500'],P.sectors.map(s=>[esc(s[0]),pp(s[1],1),pp(s[2],1)]),[1,2])}</div>`:''}</div>
${V4.next?`<div class="callout"><b>One next step:</b> ${V4.next}</div>`:''}`;
if(rows.length)table('v4pt',[['rank','#',v=>v,'num'],['t','Stock',(v,r)=>`<b>${v}</b><br><span class="mute sm">${esc(r.n)}</span>`],['s','Sector',v=>esc(v)],['w','Weight',(v,r)=>`<b>${pp(r.w_disp??v,1)}</b>`,'num'],['verdict','Diligence',v=>tierTag4(v)],['comp','Model score',v=>f1(v*100,0),'num'],['pe','NTM P/E (REITs: P/FFO)',(v,r)=>v==null?'–':f1(v)+'x'+(r.pe_label?' '+esc(r.pe_label):''),'num'],['p_pos','Base rate, similar stocks: 12m gain / beat S&P*',(v,r)=>pp(v)+' / '+pp(r.p_beat),'num'],['bear','3-yr bear / base / bull (a.r.)',(v,r)=>`<span class="bad">${spp(r.bear,0)}</span> / ${spp(r.base,0)} / <span class="ok">${spp(r.bull,0)}</span>`,'num'],['thesis','Thesis in one line',v=>esc(v),'w'],['kill','Exit if…',v=>esc((v||[]).slice(0,2).join('; ')),'w']],rows,{sort:'rank',click:t=>{v4dosT=t;go('v4dos')}});
};
let v4dosT=null;
R.v4dos=()=>{const ks=((V4.port||{}).rows||[]).slice().sort((a,b)=>a.rank-b.rank).map(r=>r.t).concat(Object.keys(V4.dossiers||{}).filter(t=>!((V4.port||{}).rows||[]).some(r=>r.t===t)));if(!ks.length){$('#app').innerHTML='<p class="mute">Dossiers pending.</p>';return}
 if(!v4dosT||!ks.includes(v4dosT))v4dosT=ks[0];const i=ks.indexOf(v4dosT);const r=((V4.port||{}).rows||[]).find(x=>x.t===v4dosT);
 $('#app').innerHTML=`<div class="controls"><label class="sm mute" for="v4ds" style="align-self:center">Company</label><select id="v4ds">${ks.map(t=>`<option value="${t}" ${t===v4dosT?'selected':''}>${t}${(V4.port.rows||[]).some(x=>x.t===t)?'':' (not held)'}</option>`).join('')}</select><button id="v4pv">Previous</button><button id="v4nx">Next</button></div>
 ${r?`<div class="grid">${kvCard('Position',[['Weight',pp(r.w,1)],['Diligence verdict',tierTag4(r.verdict)],['Model score (0–100)',f1(r.comp*100,0)],['Quality / Value / Momentum / Earnings',[r.fam.Q,r.fam.V,r.fam.M,r.fam.S].map(x=>x==null?'–':Math.round(x*100)).join(' / ')],['NTM P/E',r.pe==null?'–':f1(r.pe)+'x'],['1-yr volatility',pp(r.vol)],['P(12m gain) / P(beat S&P)*',pp(r.p_pos)+' / '+pp(r.p_beat)],['Next earnings',esc(r.next_er||'–')]],true)}${listCard('Exit (kill) criteria',r.kill,'bad')}</div>`:''}
 <div class="card" style="margin-top:14px">${(V4.dossiers||{})[v4dosT]||'<p class="mute">No dossier.</p>'}</div>`;
 $('#v4ds').onchange=e=>{v4dosT=e.target.value;R.v4dos()};$('#v4pv').onclick=()=>{v4dosT=ks[(i+ks.length-1)%ks.length];R.v4dos();window.scrollTo(0,0)};$('#v4nx').onclick=()=>{v4dosT=ks[(i+1)%ks.length];R.v4dos();window.scrollTo(0,0)};};
R.v4ev=()=>{const B=V4.bt||{};let h=`<h2 style="margin-top:0">Evidence: does the model add value on a point-in-time universe?</h2><p class="lede">${B.lede||''}</p>`;
 if(B.x)h+=`<div class="card" style="margin:12px 0"><h4>Growth of $1 (log scale), monthly, after 10 bps trading costs</h4>${lineChart({x:B.x,series:B.lines},{log:true,aria:'growth of one dollar',yfmt:v=>'$'+v,endfmt:v=>'$'+f1(v,2)})}</div>`;
 if((B.stats||[]).length)h+=`<h2>Strategy statistics</h2>${simpleTable(['Strategy','CAGR','Volatility','Sharpe','Worst fall','vs EW universe','vs S&P 500 (TR)','t-stat','Rolling 3-yr windows ahead'],B.stats.map(s=>[esc(s.name),pp(s.cagr,1),pp(s.vol,1),f1(s.sharpe,2),pp(s.mdd,1),spp(s.exc_ew),spp(s.exc_spy),f1(s.t,2),pp(s.hit36)]),[1,2,3,4,5,6,7,8])}`;
 if((B.deciles||[]).length)h+=`<h2>Does a higher score mean a higher next-year return?</h2><div class="card">${barChart(B.deciles.map(([d,v])=>['D'+d,v]),{fmt:v=>pp(v,1),xlabel:'Model-score decile (D10 = best) · average next-12-month total return',aria:'returns by decile'})}</div>`;
 if((B.calib||[]).length)h+=`<h2>Calibrated odds by score decile (what "confidence" honestly means)</h2>${simpleTable(['Decile','Stock-months','P(12m gain)','P(beat S&P)','Median 12m','Bad case (10th pct)','Good case (90th pct)','P(fall >20% within 12m)'],B.calib.map(c=>['D'+c.d,c.n,pp(c.p_pos),pp(c.p_beat),spp(c.med,0),spp(c.p10,0),spp(c.p90,0),pp(c.p_dd20)]),[1,2,3,4,5,6,7])}`;
 if((B.legacy||[]).length)h+=`<h2>The old models, re-tested on the same point-in-time data</h2>${simpleTable(['Model','CAGR','vs EW universe','vs S&P 500','Verdict'],B.legacy.map(l=>[esc(l.name),pp(l.cagr,1),spp(l.exc_ew),spp(l.exc_spy),esc(l.verdict||'')]),[1,2,3])}`;
 if((B.bias||[]).length)h+=`<h2>How much the old test method flattered results</h2>${simpleTable(['Measure','Today\'s members (v3 method)','Point-in-time members','Inflation'],B.bias.map(b=>[esc(b[0]),pp(b[1],1),pp(b[2],1),spp(b[1]-b[2])]),[1,2,3])}`;
 if((B.years||[]).length)h+=`<h2>Calendar years</h2>${simpleTable(['Year','Model top 30','EW universe','S&P 500 (TR)','Model − S&P'],B.years.map(y=>[y[0],spp(y[1]),spp(y[2]),spp(y[3]),spp(y[1]-y[3])]),[1,2,3,4])}`;
 if(B.notes)h+=`<p class="sm mute">${B.notes}</p>`;$('#app').innerHTML=h;};
R.v4risk=()=>{const K=V4.risk||{};let h=`<h2 style="margin-top:0">Risk: what could go wrong, and how often</h2><p class="lede">${K.lede||''}</p>`;
 if((K.stress||[]).length)h+=`<h2>Historical stress replays (daily data)</h2><p class="sm mute">Today's stock sleeve held through each crisis, and the mixes rebalanced quarterly as the operating rules say. The last column is the largest share in equities that would have kept that crisis within a −20% / −15% fall.</p>${simpleTable(['Episode','Dates (S&amp;P peak → trough)','Stock sleeve','S&amp;P 500','Moderate 55/15/30 (worst point)','Cautious 35/10/55 (worst point)','Defensive 15/10/75 (worst point)','Max equity share for −20% / −15%'],K.stress.map(s=>[esc(s[0]),esc(s[1]),`<span class="bad">${spp(s[2])}</span>`,spp(s[3]),spp(s[4]),spp(s[5]),spp(s[6]),pp(s[7])+' / '+pp(s[8])]),[2,3,4,5,6,7])}`;
 if(K.worst)h+=`<div class="callout">${esc(K.worst)}</div>`;
 if((K.sims||[]).length)h+=`<h2>Simulated outcomes under three sourced market scenarios</h2>${simpleTable(['Mix','Scenario','Horizon','P(profit)','P(beat S&P)','Median a.r.','P(drawdown >15%)','P(drawdown >20%)'],K.sims.map(s=>[esc(s.mix),esc(s.sc),s.h+' yr',ppr(s.p_profit),s.p_beat==null?'–':ppr(s.p_beat),spp(s.med),ppr(s.dd15),ppr(s.dd20)]),[3,4,5,6,7])}`;
 if((K.contrib||[]).length)h+=`<h2>Where the risk comes from</h2><div class="card">${hbars(K.contrib.map(c=>[c[0],c[1]]),{fmt:v=>pp(v,1)})}<p class="sm mute">Share of the stock sleeve's volatility contributed by each holding (3 years of daily returns, plain sample covariance). "SPY" is the part of the sleeve held in the index fund.</p>${K.sleeveRisk?`<p class="sm">${esc(K.sleeveRisk)}</p>`:''}</div>`;
 if(K.divers)h+=`<div class="callout">${esc(K.divers)}</div>`;
 if((K.alloc||[]).length)h+=`<h2>Allocation scenarios (arithmetic, not advice)</h2>${simpleTable(K.allocHead,K.alloc,K.allocNum||[])}`;
 if(K.notes)h+=`<p class="sm mute">${K.notes}</p>`;$('#app').innerHTML=h;};
R.v4impl=()=>{const I=V4.impl||{};$('#app').innerHTML=`<h2 style="margin-top:0">Implementation for a UAE-resident investor</h2><p class="lede">${I.lede||''}</p>
 ${(I.facts||[]).length?simpleTable(['Fact','Detail','Source'],I.facts.map(f=>[esc(f[0]),esc(f[1]),f[2]?`<a href="${f[2]}" target="_blank" rel="noopener">source</a>`:'']),[]):''}
 ${(I.rules||[]).length?`<h2>Operating rules</h2><div class="grid">${I.rules.map(r=>`<div class="card"><h4>${esc(r[0])}</h4><p class="sm">${esc(r[1])}</p></div>`).join('')}</div>`:''}
 ${(I.dollars||{}).rows?`<h2>Turning percentages into amounts</h2><p class="mute sm">Arithmetic only; which mix to use and how much to invest are your decisions.</p><ul class="pts sm">${(I.dollars.formula||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${simpleTable(I.dollars.head.map(esc),I.dollars.rows.map(r=>r.map(esc)),[1,2,3,4,5])}<p class="sm mute">Scale every figure by your total ÷ 10,000.</p>`:''}${(I.dollars||{}).estate?`<h2>US estate tax and dividend withholding at your size</h2><p class="mute sm">${esc(I.dollars.estate.note)}</p>${simpleTable(I.dollars.estate.head.map(esc),I.dollars.estate.rows.map(r=>r.map(esc)),[1,3])}<p class="sm mute">${esc(I.dollars.estate.foot)}</p>`:''}
 ${(I.steps||[]).length?`<h2>How to place the orders at IBKR (click by click)</h2><p class="mute sm">General how-to for your own use; no orders are placed for you, and amounts are your decision.</p><ol class="pts">${I.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}
 ${(I.weekly||[]).length?`<h2>Weekly 30-minute review</h2><ol class="pts">${I.weekly.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:''}
 <p class="sm mute">${I.disclaimer||''}</p>`;};
R.v4rank=()=>{const rows=V4.rank||[];$('#app').innerHTML=`<h2 style="margin-top:0">v4 ranking of all current S&amp;P 500 members</h2><p class="mute">Model score = average of four sector-neutral families (quality, value, momentum, earnings surprise), point-in-time data to ${esc(V4.asof||'')}. Click a column to sort.</p><div class="controls"><input id="v4q" type="search" placeholder="Search ticker, name, sector" aria-label="Search the ranking"></div><div class="scroll" style="max-height:700px"><table id="v4r"></table></div>`;
 const cols=[['rk','#',v=>v,'num'],['t','Ticker',(v,r)=>`<b>${v}</b>${r.inport?' <span class="tag tA">held</span>':''}`],['n','Name',v=>esc(v)],['s','Sector',v=>esc(v)],['comp','Score',v=>v==null?'–':f1(v*100,0),'num'],['Q','Quality',v=>v==null?'–':Math.round(v*100),'num'],['V','Value',v=>v==null?'–':Math.round(v*100),'num'],['M','Momentum',v=>v==null?'–':Math.round(v*100),'num'],['S','Earnings',v=>v==null?'–':Math.round(v*100),'num'],['pe','NTM P/E',v=>v==null?'–':f1(v),'num'],['vol','Vol',v=>pp(v),'num'],['gate','Status',v=>esc(v||'')]];
 const draw=q=>table('v4r',cols,rows.filter(r=>!q||(r.t+' '+r.n+' '+r.s).toLowerCase().includes(q)),{sort:'rk'});draw('');$('#v4q').oninput=e=>draw(e.target.value.toLowerCase());};
R.v4aud=()=>{const A=V4.v3audit||[];$('#app').innerHTML=`<h2 style="margin-top:0">What was wrong with v3, and what v4 does instead</h2><p class="lede">${esc(V4.v3auditLede||'')}</p>${simpleTable(['#','Severity','Finding','Evidence (re-computed)','v4 fix'],A.map((a,i)=>[i+1,`<span class="${a.sev==='Critical'?'bad':a.sev==='High'?'warn':'mute'}">${esc(a.sev)}</span>`,esc(a.f),esc(a.ev),esc(a.fix)]),[])}${V4.v3credit?`<div class="callout">${esc(V4.v3credit)}</div>`:''}`;};
R.v4meth=()=>{const M=V4.method||{};$('#app').innerHTML=`<h2 style="margin-top:0">Method and data lineage</h2>${M.prereg?`<div class="callout"><b>Pre-registered model (frozen before any v4 backtest):</b> ${esc(M.prereg)}</div>`:''}
 ${(V4.glossary||[]).length?`<div class="card" style="margin:12px 0"><h4>Plain-English glossary</h4><ul class="pts sm">${V4.glossary.map(g=>`<li><b>${esc(g[0])}:</b> ${esc(g[1])}</li>`).join('')}</ul></div>`:''}
 ${(M.steps||[]).length?`<div class="flow">${M.steps.map(s=>`<div><b>${esc(s[0])}</b><span class="sm">${esc(s[1])}</span></div>`).join('')}</div>`:''}
 ${(M.data||[]).length?`<h2>Datasets and validation</h2>${simpleTable(['Dataset','Source','Coverage','Validation'],M.data.map(d=>d.map(esc)),[])}`:''}
 ${((V4.appendix||{}).register||[]).length?`<h2>Register of independent checks</h2>${simpleTable(['Check','What it re-derived','Result','File'],V4.appendix.register.map(x=>[`<b>${esc(x[0])}</b>`,esc(x[1]),esc(x[2]),`<code>${esc(x[3])}</code>`]),[])}`:''}
 ${((V4.appendix||{}).verification||[]).length?`<h2>Per-holding verification</h2>${simpleTable(['Stock','Valuation model (V1)','Independent valuation check','Analyst view vs V1','Dossier facts checked by'],V4.appendix.verification.map(v=>[`<b>${esc(v.t)}</b>`,esc(v.v1||'–'),esc(v.check),esc(v.analyst),esc((v.facts||[]).join('; ')||'not yet checked')]),[])}`:''}
 ${(M.agents||[]).length?`<h2>Agents and what each produced</h2>${simpleTable(['Agent','Role','Key output'],M.agents.map(d=>d.map(esc)),[])}`:''}
 ${(M.limits||[]).length?listCard('Known limitations (and how each is handled)',M.limits,'warn'):''}`;};
R.v4grade=()=>{const G=V4.audits||{};const loops=G.loops||[];$('#app').innerHTML=`<h2 style="margin-top:0">Independent audit scores</h2><p class="lede">${esc(G.lede||'')}</p>
 ${loops.length?simpleTable(['Loop','Quant & data auditor','Investment-committee auditor','Client & compliance auditor','Average','Main fixes made after this loop'],loops.map(l=>[l.loop,l.A1??'–',l.A2??'–',l.A3??'–',`<b>${l.avg??'–'}</b>`,esc(l.fixes||'')]),[1,2,3,4]):'<p class="mute">Audit loop pending.</p>'}
 ${(G.latest||[]).length?`<h2>Latest scores by criterion</h2>${simpleTable(['Criterion','Quant','IC','Client','Evidence'],G.latest.map(r=>[esc(r[0]),r[1],r[2],r[3],esc(r[4]||'')]),[1,2,3])}`:''}`;};
R.v4recon=()=>{const X=V4.v005||{};const F=X.findings||[],C=X.candidates||[];const cls=st=>/CONFIRM|ADOPT/.test(st)?'ok':/CHALLENG|DISAGREE|REJECT/.test(st)?'bad':'warn';
$('#app').innerHTML=`<h2 style="margin-top:0">How this work relates to Codex release v005</h2><p class="lede">A second AI workstream (Codex) published a completed decision pack, <b>${esc(X.v005_release||'v005')}</b> (data ${esc(X.v005_data_cutoff||'')}). The shared workspace rules require each new release to check the previous one and say what it adopts, confirms, changes, rejects or leaves open. Neither release automatically overrides the other; the owner decides.</p>
${F.length?simpleTable(['Topic','Status','Codex v005','Claude v4','Effect'],F.map(f=>[`<b>${esc(f.topic)}</b>`,`<span class="${cls(f.status)}">${esc(f.status)}</span>`,esc(f.v005),esc(f.v4),esc(f.effect)]),[]):''}
${C.length?`<h2>v005's fourteen candidates, seen through v4's gates</h2>${simpleTable(['v005 rank','Stock','v005 decision','v005 max entry','Price 25 Sep','vs limit','v4 model rank','v4 valuation (base 3-yr)','v4 status'],C.map(c=>[c.v005_rank,`<b>${esc(c.t)}</b>`,esc(c.v005_decision),c.v005_limit==null?'–':'$'+f1(c.v005_limit,2),c.v4_price_2026_09_25==null?'–':'$'+f1(c.v4_price_2026_09_25,2),c.price_vs_limit==null?'–':spp(c.price_vs_limit),c.v4_rank??'–',(c.v4_V1||'–')+(c.v4_V1_base_3y==null?'':' ('+spp(c.v4_V1_base_3y,0)+')'),esc(c.v4_status)]),[0,3,4,5,6])}`:''}
${X.x1?`<div class="card"><h4>Independent check of v005's claims (agent X1)</h4><p class="sm">${X.x1.confirmed} of ${X.x1.checked} checked claims confirmed against v4's price data, issuer pages and SEC filings.</p>${(X.x1.exceptions||[]).length?`<ul class="pts sm">${X.x1.exceptions.map(e=>`<li>${esc(e)}</li>`).join('')}</ul>`:''}${(X.x1.disagreements||[]).length?`<p class="sm"><b>Method disagreement:</b> ${X.x1.disagreements.map(esc).join('; ')}</p>`:''}</div>`:'<p class="sm mute">Independent verification of v005\'s inherited claims is in progress.</p>'}
<p class="sm mute">Parents of this v4 release: ${esc((X.parents_for_v4_release||[]).join(', '))}. Research and general information, not personal advice; no trades are placed.</p>`;};
