import sys,json,pathlib,csv,datetime,hashlib,zipfile,shutil,math
sys.path.insert(0,r'C:/Users/user/eqv4/pylib');import pandas as pd
O=pathlib.Path('review/weekly/2026-09-27'); R=O/'raw_market';now=datetime.datetime.now(datetime.timezone.utc).isoformat()
P=pd.read_parquet(R/'inherited_d4_live_snapshot.parquet').set_index('ticker'); V=pd.read_csv(R/'inherited_d4_validation_prices.csv').set_index('ticker');scope=json.loads((R/'scope.json').read_text());new={x['ticker']:x for x in json.loads((R/'new_cboe_summary.json').read_text())}; old={x['ticker']:x for x in json.loads(pathlib.Path('versions/v005_2026-09-26_codex/reports/review/ready/decision_model.json').read_text())['stocks']}
webprices={'AMP':493.00,'PAYX':101.37,'MSFT':516.17,'NVDA':225.07,'ALLE':154.47,'HIG':124.23,'NTAP':201.15}
webobs=[dict(ticker=t,close=p,adj_close=p,header_close=p,market_session_date='2026-09-25',currency='USD',url=f'https://stockanalysis.com/stocks/{t.lower()}/history/',retrieved_date='2026-09-27',source='StockAnalysis historical table, directly labels S&P Global Market Intelligence as history provider',status='new_web_observation',capture='manual numeric transcription from web tool, not raw API payload') for t,p in webprices.items()]
(R/'new_web_history_observations.json').write_text(json.dumps(webobs,indent=2))
forecasts=[dict(ticker='AMP',fy0='2026-12-31',fy1='2027-12-31',eps_fy0=46.53,eps_fy1=51.67,page_updated='2026-09-22'),dict(ticker='PAYX',fy0='2027-05-31',fy1='2028-05-31',eps_fy0=5.96,eps_fy1=6.39,page_updated='2026-09-25'),dict(ticker='PGR',fy0='2026-12-31',fy1='2027-12-31',eps_fy0=18.09,eps_fy1_display='1.01K',page_updated='2026-09-24',status='reject_fy1_not_validated_by_cross_vendor_agreement')]
for f in forecasts:f.update(url=f"https://stockanalysis.com/stocks/{f['ticker'].lower()}/forecast/",retrieved_date='2026-09-27',basis='page labels non-GAAP adjusted; company-specific definition and field-level vintage not verified',source='S&P Global via StockAnalysis')
(R/'new_web_forecast_observations.json').write_text(json.dumps(forecasts,indent=2))
# Recompute all 503 inherited quote comparisons from release data and inspect original provider cache.
rawdir=pathlib.Path(r'C:/Users/user/eqv4/cache/d4/indep_prices'); priorout=R/'inherited_provider_cache';priorout.mkdir(exist_ok=True);rawchecks=[]
for t,v in V.iterrows():
 f=rawdir/f'cboe_{t}.json'; rec={'ticker':t,'cache_available':f.exists()}
 if f.exists():
  b=f.read_bytes();q=json.loads(b);(priorout/f.name).write_bytes(b);d=q.get('data',{});rec.update(source_url=q.get('_url'),retrieved_utc=q.get('_retrieved_utc'),cache_sha256=hashlib.sha256(b).hexdigest(),raw_close=d.get('close'),csv_close=v.cboe_close,match_raw_csv=d.get('close')==v.cboe_close,identity_ok=d.get('symbol','').replace('.','-')==t,session_date=str(d.get('last_trade_time',''))[:10])
 rawchecks.append(rec)
for f in rawdir.glob('cnbc_*.json'):shutil.copyfile(f,priorout/f.name)
(R/'inherited_raw_reconciliation.json').write_text(json.dumps(rawchecks,indent=2))
quality=P.ntm_quality.value_counts().to_dict();changes=[];rows=[]
def clean(x):
 if pd.isna(x):return None
 return x.item() if hasattr(x,'item') else x
fields=['cik','name_wiki','y_currency','y_quoteType','y_exchange','regularMarketTime_utc','retrieved_utc_start','retrieved_utc_end','eps_fy0','eps_fy1','eps_fy0_n','eps_fy1_n','eps_fy1_low','eps_fy1_high','eps_fy0_rev30_pct','eps_fy1_rev30_pct','forwardEps','fy0_end','fy1_end_trend','eps_ntm','pe_ntm','ntm_quality','ntm_flags','next_earnings_date','next_earnings_is_estimate','y_lastSplitDate','y_lastSplitFactor','y_exDividendDate','y_prevName','y_nameChangeDate']
for t in scope['tickers']:
 p=P.loc[t];v=V.loc[t];n=new.get(t,{}); price=webprices.get(t,float(p.price));basis='USD per listed share, regular-session close; not executable quote'
 good=n.get('http_status')==200 and str(n.get('last_trade_time',''))[:10]=='2026-09-25' and n.get('response',{}).get('data',{}).get('symbol')==t
 delta=None if n.get('close') is None else n['close']-price
 conflict='none' if delta is not None and abs(delta)<1e-8 else 'fractional_cent_source_difference' if delta is not None and abs(delta)<=.00501 else 'source_difference_requires_review'
 row={'ticker':t,'market_session_date':'2026-09-25','currency':str(p.y_currency),'accepted_close':price,'accepted_close_status':'inherited_Sep25_close_newly_corroborated' if good and abs(delta)<=.00501 else 'inherited_close_only_pending_new_corroboration','price_basis':basis,'original_v005_reference':old.get(t,{}).get('reference_price'),'original_v005_reference_date':old.get(t,{}).get('reference_date'),'inherited_v011_close':float(p.price),'inherited_cboe_close':float(v.cboe_close),'inherited_cnbc_last':float(v.cnbc_last),'inherited_cnbc_time':v.cnbc_last_time,'new_cboe_close':n.get('close'),'new_cboe_url':n.get('url'),'new_cboe_retrieved_utc':n.get('retrieved_utc'),'new_cboe_last_trade_time':n.get('last_trade_time'),'new_cboe_provider_timestamp':n.get('provider_timestamp'),'new_cboe_identity_date_pass':good,'new_cboe_minus_accepted_close':delta,'new_cboe_minus_inherited_close':None if n.get('close') is None else n['close']-float(p.price),'source_conflict_status':conflict,'new_web_history_close':webprices.get(t),'new_web_history_url':f'https://stockanalysis.com/stocks/{t.lower()}/history/' if t in webprices else None,'new_web_history_status':'newly_observed' if t in webprices else 'not_attempted_no_claim','inherited_forecast':{k:clean(p[k]) for k in fields},'forecast_origin':'unchanged Sep25 snapshot reused from v011; not a new analyst-feed pull','forecast_accepted_for_automatic_valuation':False,'forecast_usable_as_context_only':t!='PGR' and p.ntm_quality=='ok','ntm_label':'annual time-weighted approximation; not verified four-quarter NTM','event_sweep_status':'inherited vendor calendar only; full new SEC/IR event audit delegated to other workstream'}
 if t in old:row.update(existing_limit=old[t]['limit_price'],below_existing_limit_price_only=price<=old[t]['limit_price'],change_vs_v005_reference_pct=(price/old[t]['reference_price']-1)*100)
 if t=='MSFT':row['v005_correction']='516.05 replaced with516.17 for sameSep25 session; newdatedhistory/Cboe plus archivedYahoo/CNBC corroborate'
 if t=='PGR':row['forecast_rejection']='FY1 EPS1012.0, one contributor; derived NTM747.864 invalid. v011 dossier already explicitly quarantines; public second vendor repeats1.01K, not validation.'
 if t=='NTAP':row['price_resolution']='Accept201.15 shown by datedStockAnalysis history and archivedCNBC; retain Cboe201.145 as unrounded source discrepancy, not exact match.'
 if t=='RL':row['corporate_action_note']='Sep25 $1 dividend event; current historical adjusted closes before event differ from frozenSep24 vintage. Use rawclose for price-reference comparison; total-return calculation needs dividend.'
 rows.append(row)
coverage={'universe_rows':len(P),'inherited_dated_Sep25_prices':int((P.regularMarketDate_ny=='2026-09-25').sum()),'inherited_USD_prices':int((P.y_currency=='USD').sum()),'inherited_cboe_within_0_5pct':int(((V.cboe_close/V.price-1).abs()<=.005).sum()),'inherited_cnbc_within_0_5pct':int(((V.cnbc_last/V.price-1).abs()<=.005).sum()),'inherited_cboe_exact_tolerance_1e6_relative':int(((V.cboe_close/V.price-1).abs()<1e-6).sum()),'inherited_cboe_exact':int(((V.cboe_close-V.price).abs()<1e-8).sum()),'inherited_cnbc_exact':int(((V.cnbc_last-V.price).abs()<1e-8).sum()),'inherited_raw_cboe_available':sum(x['cache_available'] for x in rawchecks),'inherited_raw_cboe_csv_matches':sum(x.get('match_raw_csv',False) for x in rawchecks),'inherited_raw_cboe_identity_matches':sum(x.get('identity_ok',False) for x in rawchecks),'new_Cboe_attempted':len(new),'new_Cboe_valid_scope_prices':sum(r['new_cboe_identity_date_pass'] for r in rows),'new_web_history_names':len(webprices),'new_web_forecast_names':len(forecasts),'not_newly_price_refetched_universe':len(P)-len(new),'scope_unique_names':len(rows),'scope_source_conflicts':[r['ticker'] for r in rows if r['source_conflict_status']!='none'],'inherited_ntm_quality':quality}
res={'author':'Codex market subaudit','status':'draft weekly research inputs; not trading authorization','parents':['v011_2026-09-27_claude','v005_2026-09-26_codex'],'prepared_utc':now,'data_cutoff':'2026-09-25 completed US regular session; inherited forecasts retrievedSep25, fresh quotes retrievedSep27','coverage':coverage,'rows':rows,'failed_or_unavailable':[{'source':'web finance tool','status':'no tool response for six ticker batch; rejected as data source'},{'source':'new consensus feed all34','status':'not acquired; reuse datedSep25 snapshot, direct public displays on3 only'},{'source':'FinancialDatasets/FMP','status':'not queried in this weekly subaudit; no paid access or inherited auth assumed'}],'limitations':['Provider cache timestamps may beSep26 while underlying session remainsSep25. These are not live order prices.','Three-host agreement does not certify upstream feed independence or exchange official-close status.','503-field reconciliation is reuse and recalculation of inherited data, not503 newly downloaded quotes.','EPS annual time-weighting remains approximate; malformed denominators require hard exclusion.','New primary event checks onlyAMP andNTAP here; no claim of exhaustive absence of adverse news for34.']}
res['fund_identity_checks']=json.loads((R/'fund_identity_checks.json').read_text()) if (R/'fund_identity_checks.json').exists() else []
res['material_event_review']=json.loads((R/'event_reconciliation_addendum.json').read_text()) if (R/'event_reconciliation_addendum.json').exists() else {}
(O/'market_audit.json').write_text(json.dumps(res,indent=2,allow_nan=False,default=str))
print(json.dumps(coverage,indent=2));print('schema',list(rows[0]));print('allprices',[(r['ticker'],r['accepted_close']) for r in rows])



