from pathlib import Path
import json
P=Path('review/ready'); W=Path('review/weekly/2026-09-27')
market=json.loads((W/'market_audit.json').read_text())
cfg={'prepared':'2026-09-27 Dubai','decision_cutoff':'Prices: 2026-09-25 completed US regular session. Information: public filings/events checked 2026-09-27; individual availability timestamps retained.','parents':['v005_2026-09-26_codex','v011_2026-09-27_claude'],'weekly_report':'../weekly/2026-09-27/WEEKLY_REVIEW.md','stocks':{x['ticker']:{'reference_price':x['accepted_close'],'reference_date':x['market_session_date'],'price_source':x['new_cboe_url'],'price_conflict':x['source_conflict_status']} for x in market['rows']},'funds':{'VUAA':{'nav':149.7632,'nav_date':'2026-09-25'},'IB01':{'nav':121.89,'nav_date':'2026-09-25'}},'coverage':market['coverage']}
for t,x in cfg['stocks'].items():
    x['decision']='BUY' if t in ['AMP','PAYX'] else 'WAIT'
cfg['stocks']['HIG']['condition']='WAIT: reference price exceeds $120. Before entry reconcile the September 25 post-close commutation settlement and capital effects. The $393m expected GAAP gain is excluded from core EPS; the $1.5bn reinsurance limit was already exhausted. Price alone does not authorize a purchase.'
(P/'weekly_override.json').write_text(json.dumps(cfg,indent=2))
f=P/'build_decision_pack.py'; s=f.read_text(encoding='utf-8')
s=s.replace("P=Path(__file__).resolve().parent", "P=Path(__file__).resolve().parent\nWEEKLY=json.loads((P/'weekly_override.json').read_text(encoding='utf-8')) if (P/'weekly_override.json').exists() else {}",1)
s=s.replace("if t=='MSFT': ref=516.05;date='2026-09-25'", "if t=='MSFT': ref=516.05;date='2026-09-25'\n    update=WEEKLY.get('stocks',{}).get(t,{})\n    ref=update.get('reference_price',ref);date=update.get('reference_date',date)")
s=s.replace("    sources=s.get('sources',[])", "    decision=update.get('decision',decision)\n    sources=s.get('sources',[])",1)
s=s.replace("if decision=='BUY NOW' else 0", "if decision in ['BUY NOW','BUY'] else 0")
s=s.replace("    for s in ss:add(s,kind,d)", "    for s in ss:add(s,kind,d)")
s=s.replace("S.sort(key=lambda x:x['rank']);", "for stock in S:\n    update=WEEKLY.get('stocks',{}).get(stock['ticker'],{})\n    if update.get('condition'): stock['condition']=update['condition']\n    stock['price_source']=update.get('price_source')\n    stock['price_conflict']=update.get('price_conflict')\n    for case in stock['scenarios']:\n        case['irr_reference_after_30pct_withholding_25bp_costs']=irr(stock['reference_price']*1.0025,case['terminal_price']*.9975,case['dividends'],.30)\n        case['irr_limit_after_30pct_withholding_25bp_costs']=irr(stock['limit_price']*1.0025,case['terminal_price']*.9975,case['dividends'],.30)\n        case['pv_hurdle_after_30pct_withholding_25bp_costs']=pv(case['terminal_price']*.9975,case['dividends'],stock['hurdle'],.30)/1.0025\n    stock['base_ceiling_after_costs']=next(c['pv_hurdle_after_30pct_withholding_25bp_costs'] for c in stock['scenarios'] if c['name']=='base')\nS.sort(key=lambda x:x['rank']);")
s=s.replace("portfolios=[]", "for fund in funds:\n    fund.update(WEEKLY.get('funds',{}).get(fund['ticker'],{}))\n\nportfolios=[]",1)
s=s.replace("(P/'decision_model.json').write_text", "model.update({k:WEEKLY[k] for k in ['prepared','decision_cutoff','parents','weekly_report','coverage'] if k in WEEKLY})\n(P/'decision_model.json').write_text",1)
s=s.replace("Prospective investment decisions, dated 26 September 2026 Dubai.","Prospective investment decisions, dated 27 September 2026 Dubai.")
s=s.replace("wb.close()", "ws=wb.add_worksheet('Weekly audit');ws.set_column('A:A',30);ws.set_column('B:B',115);ws.write_row(0,0,['Field','Weekly evidence / scope'],head)\nfor row,(key,value) in enumerate([('Prepared',model['prepared']),('Cutoff',model['decision_cutoff']),('Parents','; '.join(WEEKLY.get('parents',[]))),('Coverage',json.dumps(WEEKLY.get('coverage',{}))),('Actions','BUY AMP <=500 and PAYX <=101.80, up to2% each, only if live price/thesis/capacity pass; WAIT on other names. No actual holdings supplied.'),('HIG event',WEEKLY.get('stocks',{}).get('HIG',{}).get('condition','')),('Valuation facts','42 operating scenarios retained; 34 prices freshly corroborated. 469 other universe prices reused from dated immutable archive.'),('Limit cost gate','Ceilings tested with30% dividend withholding plus25bp entry and25bp exit. Personal capital-gains tax and fixed dealing fees are unknown.'),('Report',WEEKLY.get('weekly_report',''))],1):\n ws.write(row,0,key,head);ws.write(row,1,value,wrap);ws.set_row(row,60)\nws=wb.add_worksheet('After costs');ws.set_column('A:G',24);ws.write_row(0,0,['Ticker','Case','IRR reference net','IRR limit net','PV at hurdle net','Published limit','Cost assumptions'],head)\nr=1\nfor stock in S:\n for case in stock['scenarios']:\n  ws.write_row(r,0,[stock['ticker'],case['name'],case['irr_reference_after_30pct_withholding_25bp_costs'],case['irr_limit_after_30pct_withholding_25bp_costs'],case['pv_hurdle_after_30pct_withholding_25bp_costs'],stock['limit_price'],'30% dividend tax;25bp entry/exit']);r+=1\nwb.close()",1)
f.write_text(s,encoding='utf-8')
print('Weekly input and model builder prepared; prior state preserved.')
